import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/dom.mjs';
const conta={id:'fonte-1',banco:'Banco Exemplo',titular:'Empresa Alfa',agencia:'001',conta:'123-4',doc:'12345678000199',pix:'contato@example.com'};
function app(){const a=setup();a.run("E=structuredClone(SEED);E.bancos=[];E.empresasPJ=[];globalThis.gravacoes=0;agendaPush=()=>gravacoes++;apiSync=async()=>({contas:[],lidoEm:new Date().toISOString()});atual='bancos';menu();");a.ctx.origem=[conta];return a;}
test('bancos entra em Dinheiro e abrir a origem não grava dados',async()=>{const a=app();a.run('apiSync=async()=>({contas:origem})');await a.run("vBancos(document.querySelector('#main'))");assert.equal(a.run('E.bancos.length'),0);assert.equal(a.run('gravacoes'),0);assert.equal(a.document.querySelectorAll('.banco-card').length,1);assert.match(a.document.querySelector('.banco-card').textContent,/Gestão Impresilk/);assert.equal(a.run("MODS.slice(0,MODS.findIndex(m=>m.id==='bancos')+1).filter(m=>m.grupo).at(-1).grupo"),'Dinheiro');});
test('mesma conta é reunida mesmo quando o cadastro local não tem documento',()=>{const a=app();a.run("E.bancos=[{...origem[0],id:'local',doc:'',obs:'Nota local'}]");const antes=a.run('JSON.stringify(E)');assert.equal(a.run('bancosReunidos(E.bancos,origem).length'),1);assert.equal(a.run('bancosReunidos(E.bancos,origem)[0]._local.obs'),'Nota local');assert.equal(a.run('JSON.stringify(E)'),antes);});
test('contas diferentes, documentos conflitantes e identificação incompleta não se misturam',()=>{const a=app();for(const patch of [{conta:'987-6'},{titular:'Empresa Beta',doc:'',agencia:''},{doc:'00000000000001'},{conta:''}]){a.ctx.local={...conta,...patch,id:'local'};assert.equal(a.run('bancosReunidos([local],origem).length'),2);}assert.equal(a.run("bancosIguais({banco:'',conta:'1',titular:'A'},{banco:'',conta:'1',titular:'A'})"),false);});
test('guardar é explícito e idempotente, inclusive para contas sem número',()=>{const a=app();a.ctx.origem=[conta,{...conta,id:'fonte-2',conta:''}];a.run('bancosConferirImportacao(origem)');assert.equal(a.run('E.bancos.length'),0);a.document.querySelector('#modais button').click();assert.equal(a.run('E.bancos.length'),0);assert.equal(a.run('bancosGuardar(origem)'),2);assert.equal(a.run('bancosGuardar(origem)'),0);assert.equal(a.run('gravacoes'),1);assert.equal(a.run('E.bancos[0].origemGestao'),'fonte-1');});
test('falha da origem não vira lista completa vazia e mantém contas locais',async()=>{const a=app();a.run("E.bancos=[{...origem[0],id:'local'}];apiSync=async()=>{throw Error('rede')}");await a.run("vBancos(document.querySelector('#main'))");assert.match(a.document.querySelector('[role=alert]').textContent,/ainda não estão incluídas/);assert.match(a.document.querySelector('.bancos-origem').textContent,/origem indisponível/);assert.equal(a.document.querySelectorAll('.banco-card').length,1);assert.equal(a.run('gravacoes'),0);});
test('atualização com falha preserva última leitura e cache evita consultas repetidas',async()=>{const a=app();a.run('globalThis.leituras=0;apiSync=async()=>{leituras++;return {contas:origem,lidoEm:new Date().toISOString()}}');await a.run('bancosCarregar()');await a.run('bancosCarregar()');assert.equal(a.run('leituras'),1);a.run("apiSync=async()=>{throw Error('rede')}");await a.run('bancosCarregar(true)');assert.equal(a.run('bancosFonte.contas.length'),1);assert.match(a.run('bancosFonte.erro'),/Não foi possível/);});
test('busca e titular filtram contas sem alterar o cadastro',async()=>{const a=app();a.ctx.origem=[conta,{...conta,id:'fonte-2',banco:'Banco Outro',titular:'Empresa Beta',conta:'234-5'}];a.run('apiSync=async()=>({contas:origem})');await a.run("vBancos(document.querySelector('#main'))");const input=a.document.querySelector('[aria-label="Buscar conta"]');input.value='Outro';input.oninput();assert.equal(a.document.querySelectorAll('.banco-card').length,1);assert.match(a.document.querySelector('.banco-card').textContent,/Empresa Beta/);assert.equal(a.run('gravacoes'),0);});
test('formulário distingue campos obrigatórios e rejeita conta repetida',()=>{const a=app();a.run("E.bancos=[{...origem[0],id:'local'}];bancoModal()");const f=a.document.querySelector('#modais form');const before=a.run('JSON.stringify(E.bancos)');f.querySelector('[name=banco]').value=conta.banco;f.onsubmit({preventDefault(){}});assert.equal(a.run('JSON.stringify(E.bancos)'),before);f.querySelector('[name=titular]').value=conta.titular;f.querySelector('[name=agencia]').value=conta.agencia;f.querySelector('[name=conta]').value=conta.conta;f.onsubmit({preventDefault(){}});assert.equal(a.run('E.bancos.length'),1);assert.match(f.textContent,/já está cadastrada/);});
test('busca global abre o cadastro bancário e cancelar exclusão preserva dados',()=>{const a=app();a.run("E.bancos=[{...origem[0],id:'local'}];abrirRegistro('guia','bancos',E.bancos[0])");assert.equal(a.run('atual'),'bancos');assert.equal(a.document.querySelector('#modais [name=banco]').value,conta.banco);a.run('bancoExcluir(E.bancos[0])');assert.equal(a.run('E.bancos.length'),1);assert.equal(a.run('gravacoes'),0);});
test('excluir cópia local não altera cadastro de origem e formulário obsoleto não recria conta',()=>{const a=app();a.run("E.bancos=[{...origem[0],id:'local'}];globalThis.antiga=E.bancos[0];bancoModal(antiga);confirm=()=>true;bancoExcluir(antiga)");assert.equal(a.run('E.bancos.length'),0);assert.equal(a.ctx.origem.length,1);a.document.querySelector('#modais form').onsubmit({preventDefault(){}});assert.equal(a.run('E.bancos.length'),0);assert.match(a.document.querySelector('#modais form').textContent,/removido/);});

test('mesma identidade bancária reúne nomes abreviados sem alterar titulares e sinaliza a diferença',async()=>{const a=app();a.ctx.origem=[{...conta,banco:'BB',titular:'Alfa Ltda'}];a.run("E.bancos=[{...origem[0],id:'local',banco:'Banco do Brasil',titular:'Alfa',doc:''}];apiSync=async()=>({contas:origem})");const antes=a.run('JSON.stringify(E.bancos)');await a.run("vBancos(document.querySelector('#main'))");assert.equal(a.document.querySelectorAll('.banco-card').length,1);assert.match(a.document.querySelector('.banco-titular-origem').textContent,/Alfa Ltda/);assert.equal(a.run('JSON.stringify(E.bancos)'),antes);assert.equal(a.run('gravacoes'),0);});

test('filtro de titular removido volta a todos sem esconder as demais contas',async()=>{const a=app();a.run("filtro.bancoTitular='Titular removido';apiSync=async()=>({contas:origem})");await a.run("vBancos(document.querySelector('#main'))");assert.equal(a.run('filtro.bancoTitular'),'');assert.equal(a.document.querySelectorAll('.banco-card').length,1);});
