import {test} from 'node:test';import assert from 'node:assert/strict';import {setup} from './helpers/dom.mjs';
function app(){const a=setup();a.run("E=structuredClone(SEED);E.desenvolvimento={fontes:[],leituras:[],revisoes:[],reflexoes:[],validacoes:[]};filtro.guiaAba='desenvolvimento';atual='guia'");return a}
test('Desenvolvimento abre todos os formulários de entrada',()=>{for(const fn of ['devModalRevisao','devModalReflexao','devModalFonte','devModalAcao']){const {run,document}=app();assert.doesNotThrow(()=>run(fn+'()'));assert.ok(document.querySelector('form.dev-form'))}});
test('Avaliação preserva zero como nota e mantém cópias independentes por data',()=>{const {run}=app();run("devSalvarRevisao({'Saúde':0,'Família':8},'Primeira','2026-01-01');devSalvarRevisao({'Saúde':5},'Segunda','2026-02-01')");assert.equal(run('E.desenvolvimento.revisoes[0].notas.Saúde'),0);assert.equal(run('E.desenvolvimento.rodaAtual.Saúde'),5);assert.equal(run("devComparar({Saúde:5},{Saúde:0})[0].delta"),5);assert.equal(run("devComparar({Saúde:5},{})[0].delta"),null);run("devSalvarRevisao({Saúde:3},'Retroativa','2026-01-10')");assert.equal(run('E.desenvolvimento.rodaAtual.Saúde'),5);assert.throws(()=>run("devSalvarRevisao({},'','2026-01-01')"),/Avalie/);assert.throws(()=>run("devSalvarRevisao({Saúde:3},'','2099-01-01')"),/data/)});
test('Legado não inventa avaliação datada nem confunde zero antigo com resposta',()=>{const {run}=app();run("E.roda={Saúde:0,Lazer:7};prepararDesenvolvimento(E)");assert.equal(run('E.desenvolvimento.revisoes.length'),0);assert.equal(run('E.desenvolvimento.rodaAtual.Saúde'),undefined);assert.equal(run('E.desenvolvimento.rodaAtual.Lazer'),7);assert.equal(run('E.roda.Saúde'),0)});
test('Leitura revisada guarda histórico e ação não duplica por cliques repetidos',()=>{const {run}=app();run("const l={id:'leitura',titulo:'Escutar',texto:'Síntese',passo:'Ouvir antes de responder'};E.desenvolvimento.leituras=[l];devValidar(l,'Reconheço','Exemplo');devValidar(l,'Não me representa','Mudou');devCriarAcao(l);devCriarAcao(l)");assert.equal(run('E.desenvolvimento.validacoes.length'),2);assert.equal(run('E.desenvolvimento.validacoes[0].nota'),'Exemplo');assert.equal(run('E.pdi.length'),1)});
test('Desenvolvimento abre retrato e atalhos revelam painel correto sem sumir cadastro',()=>{const {run,document}=app();run('tela()');assert.equal(document.querySelector('#dev-retrato').hidden,false);assert.equal(document.querySelector('#dev-avaliacao').hidden,true);assert.equal(document.querySelectorAll('#guia-desenvolvimento input[type=range]').length,0);run("abreBloco('gu-pdi');tela()");assert.equal(document.querySelector('#dev-acao').hidden,false);assert.equal(document.querySelector('#dev-retrato').hidden,true);assert.ok(document.querySelector('[data-bid=gu-comport]'))});
test('Fonte mantém data de aplicação separada da modificação e bloqueia links executáveis',()=>{const {run,document}=app();run("E.desenvolvimento.fontes=[{id:'f',titulo:'Relatório teste',tipo:'Relatório',dataDocumento:'2025-12-05',atualizadoEm:'2026-06-01',url:'javascript:alert(1)',resumo:'<script>ruim</script>'}];tela()");assert.match(document.querySelector('.dev-hero').textContent,/05\/12\/2025/);assert.doesNotMatch(document.querySelector('.dev-hero').textContent,/01\/06\/2026/);assert.equal(document.querySelector('a[href^="javascript"]'),null);assert.equal(document.querySelector('.dev-history-body script'),null)});
test('Formulário cancelado não cria reflexão e salvar registra somente o preenchido',()=>{const {run,document}=app();run('devModalReflexao()');assert.equal(run('E.desenvolvimento.reflexoes.length'),0);const f=document.querySelector('.dev-form');f.querySelector('[name=titulo]').value='Reunião';f.querySelector('[name=aprendizado]').value='Perguntar antes de concluir';f.onsubmit({preventDefault(){}});assert.equal(run('E.desenvolvimento.reflexoes.length'),1);assert.equal(run('E.desenvolvimento.reflexoes[0].aprendizado'),'Perguntar antes de concluir')});
test('Backup preserva fontes e história e rejeita listas inválidas',()=>{const {run}=app();run("E.desenvolvimento.reflexoes=[{id:'x',titulo:'Aprendizado',data:'2026-01-01'}];const json=JSON.stringify(E);localStorage.getItem=()=>json;E=carregar()");assert.equal(run('E.desenvolvimento.reflexoes.length'),1);assert.doesNotThrow(()=>run('validarBackup(E)'));run("E.desenvolvimento.fontes='inválido'");assert.throws(()=>run('validarBackup(E)'),/desenvolvimento.fontes/)});
