import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/dom.mjs';
import {modals} from './helpers/design-cases.mjs';
function missingLabels(document,root){return [...root.querySelectorAll('input:not([hidden]),select,textarea')].filter(x=>x.type!=='hidden'&&!x.getAttribute('aria-label')&&!x.getAttribute('aria-labelledby')&&!x.closest('label')&&![...document.querySelectorAll('label')].some(l=>l.htmlFor&&l.htmlFor===x.id)).map(x=>x.outerHTML.slice(0,120));}
for(const [name,code] of modals)test('Design: janela '+name+' tem título e campos identificados',async()=>{const {run,document}=setup();run(code);await Promise.resolve();const root=document.querySelector('[role="dialog"]');assert.ok(root);assert.ok(document.getElementById(root.getAttribute('aria-labelledby')));assert.deepEqual(missingLabels(document,root),[]);assert.equal(document.querySelector('.app').hasAttribute('inert'),true);});
for(const id of ['inicio','rendimentos','gastos','patrimonio','caixavgv','viagens','agenda','demandas','saude','estrategia','fortemais','oportunidades','documentos','guia','config'])test('Design: campos e filtros identificados em '+id,async()=>{const {run,document}=setup();run(`atual='${id}';tela()`);await Promise.resolve();assert.deepEqual(missingLabels(document,document.querySelector('#main')),[])});
test('Design: janela sobre janela isola cada camada e libera o painel ao fechar',()=>{const {run,document}=setup();run("abrirModal('Primeira','',c=>{});abrirModal('Segunda','',c=>{})");const [first,second]=document.querySelectorAll('.fundo');assert.equal(first.hasAttribute('inert'),true);assert.equal(second.hasAttribute('inert'),false);second.querySelector('.fechar').click();assert.equal(first.hasAttribute('inert'),false);assert.equal(first.hasAttribute('aria-hidden'),false);assert.equal(document.querySelector('.app').getAttribute('aria-hidden'),'true');first.querySelector('.fechar').click();assert.equal(document.querySelector('.app').hasAttribute('inert'),false);assert.equal(document.querySelector('.app').hasAttribute('aria-hidden'),false)});
test('Design: anexos e importação oferecem botão de teclado',()=>{const {run,ctx}=setup();ctx.files=run("areaArquivos('teste')");assert.equal(ctx.files.querySelector('.solta').tagName,'BUTTON');const erp=run('blocoImportarObra()');assert.equal(erp.querySelector('.solta').tagName,'BUTTON');});
test('Design: erro de entrada é anunciado e não depende apenas da cor',()=>{const {run,document}=setup();run('telaLogin()');assert.equal(document.querySelector('.erro').getAttribute('role'),'alert')});
test('Design: fechamento devolve o foco ao botão recriado pela tela',()=>{const {run,document}=setup();const old=document.createElement('button');old.textContent='Nova ficha';document.querySelector('#main').appendChild(old);Object.defineProperty(document,'activeElement',{configurable:true,value:old});let focused;document.defaultView.HTMLElement.prototype.focus=function(){focused=this};run("abrirModal('Ficha','',c=>{});tela=()=>{document.querySelector('#main').innerHTML='<button>Nova ficha</button>'}");document.querySelector('.fechar').click();assert.equal(focused,document.querySelector('#main button'));assert.notEqual(focused,old)});
test('Design: ficha de viagem identifica também os campos adicionados',()=>{const {run,document}=setup();run(modals[0][1]);for(const label of ['+ Trecho','🏨 Hospedagem','🎟️ Ingresso','🚗 Carro','+ Lançar custo']){const button=[...document.querySelectorAll('.modal button')].find(b=>b.textContent===label);assert.ok(button,label);button.click();}assert.deepEqual(missingLabels(document,document.querySelector('.modal')),[])});
