import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setup} from './helpers/dom.mjs';
const script=readFileSync(new URL('../publico/documentos-revisao.js',import.meta.url),'utf8');
function app(){const a=setup();a.run(script);a.ctx.gravacoes=0;a.ctx.localStorage.setItem=k=>{if(k==='centralLeo.v1')a.ctx.gravacoes++};return a}
function pacote(tipo='exame'){const comportamento=tipo==='leitura';return {schema:'central-leo.documentos.v1',fontes:[{id:'fonte-1',grupo:comportamento?'comportamento':'saude',titulo:'Relatório de teste',tipo:'Relatório',url:'https://drive.google.com/file/d/fonte-1/view',dataDocumento:'2026-02-10',versao:'1',lido:true,resumo:'Leitura de teste',limites:'Contexto datado'}],itens:[{id:'item-1',tipo,fonteId:'fonte-1',data:'2026-02-10',pagina:'2',titulo:'Resultado de teste',exame:'LDL',valor:'140,5',unidade:tipo==='peso'?'kg':'mg/dL',referencia:'Intervalo do laudo',texto:'Texto de teste',area:'Pessoal',passo:'Experimentar',medida:'Observar'}]}}
function preparar(a,p=pacote()){a.ctx.pacote=p;return a.run('var p=docPacote(pacote);p')}
function aplicar(a,keys=['fonte:fonte-1','item:item-1']){a.ctx.keys=keys;return a.run('docAplicar(p,keys,E,E._mt)')}
test('Documentos: ler e mostrar a revisão não altera dados',()=>{const a=app();preparar(a);const antes=a.run('JSON.stringify(E)');a.run('docMostrarRevisao(p)');assert.equal(a.run('JSON.stringify(E)'),antes);assert.equal(a.run('gravacoes'),0);assert.ok([...a.document.querySelectorAll('input[type=checkbox]')].every(x=>!x.checked));assert.equal([...a.document.querySelectorAll('button')].find(x=>/Guardar 0/.test(x.textContent)).disabled,true)});
test('Documentos: selecionar item mostra a fonte na mesma seleção; desmarcar fonte retira dependentes',()=>{const a=app();preparar(a);a.run('docMostrarRevisao(p)');const [fonte,item]=a.document.querySelectorAll('input[type=checkbox]');item.checked=true;item.onchange();assert.equal(fonte.checked,true);assert.match(a.document.querySelector('.doc-revisao [role=status]').textContent,/1 fonte\(s\) \+ 1 informação/);fonte.checked=false;fonte.onchange();assert.equal(item.checked,false);assert.equal(a.run('gravacoes'),0)});
test('Documentos: cancelar revisão não cria cadastros ou fontes',()=>{const a=app();preparar(a);a.run('docMostrarRevisao(p)');[...a.document.querySelectorAll('#modais button')].find(x=>x.textContent==='Cancelar').click();assert.equal(a.run('E.exames.length'),0);assert.equal(a.run('E.acervoDocumental.length'),0);assert.equal(a.run('gravacoes'),0)});
test('Documentos: só itens selecionados entram e a origem acompanha o exame',()=>{const a=app();const p=pacote();p.itens.push({...p.itens[0],id:'item-2',exame:'HDL',valor:'50'});preparar(a,p);assert.equal(aplicar(a),2);assert.equal(a.run('E.exames.length'),1);assert.equal(a.run('E.exames[0].exame'),'LDL');assert.equal(a.run('E.exames[0].origemDocumental.pagina'),'2');assert.equal(a.run('E.exames[0].referenciaLaudo'),'Intervalo do laudo');assert.equal(a.run('gravacoes'),1)});
test('Documentos: sem fonte selecionada não há escrita parcial',()=>{const a=app();preparar(a);assert.throws(()=>aplicar(a,['item:item-1']),/fonte/);assert.equal(a.run('E.exames.length'),0);assert.equal(a.run('gravacoes'),0)});
test('Documentos: nova versão de dados bloqueia confirmação antiga',()=>{const a=app();preparar(a);a.run('var anterior=E;E=structuredClone(E)');assert.throws(()=>a.run('docAplicar(p,["fonte:fonte-1"],anterior,anterior._mt)'),/dados mudaram/);assert.equal(a.run('gravacoes'),0)});
test('Documentos: mudança na mesma base também bloqueia confirmação',()=>{const a=app();preparar(a);a.run('E._mt=10;var versao=E._mt;E._mt=11');assert.throws(()=>a.run('docAplicar(p,["fonte:fonte-1"],E,versao)'),/dados mudaram/)});
test('Documentos: reimportação mantém edição manual sem duplicar',()=>{const a=app();preparar(a);aplicar(a);a.run('E.exames[0].valor="141"');assert.equal(a.run('docPlano(p).find(x=>x.tipo==="exame").status'),'existente');assert.throws(()=>aplicar(a),/seleção mudou/);assert.equal(a.run('E.exames[0].valor'),'141')});
test('Documentos: mesma medição de outra cópia do PDF é reconhecida',()=>{const a=app();preparar(a);a.run('E.exames=[{id:"anterior",data:"2026-02-10",exame:"ldl",valor:140.5,unidade:"mg/dL"}]');assert.equal(a.run('docPlano(p)[1].status'),'existente')});
test('Documentos: valor conflitante é bloqueado e preservado',()=>{const a=app();preparar(a);a.run('E.exames=[{id:"anterior",data:"2026-02-10",exame:"LDL",valor:90,unidade:"mg/dL"}]');assert.equal(a.run('docPlano(p)[1].status'),'conflito');assert.throws(()=>aplicar(a),/seleção mudou/);assert.equal(a.run('E.exames[0].valor'),90)});
test('Documentos: unidades diferentes não são somadas ou convertidas',()=>{const a=app();preparar(a);a.run('E.exames=[{id:"anterior",data:"2026-02-10",exame:"LDL",valor:3.6,unidade:"mmol/L"}]');assert.equal(a.run('docPlano(p)[1].status'),'novo')});
test('Documentos: cópias dentro do pacote não viram duas medições',()=>{const a=app(),p=pacote();p.itens.push({...p.itens[0],id:'copia'});preparar(a,p);assert.equal(a.run('docPlano(p)[2].status'),'existente')});
test('Documentos: resultado com sinal permanece texto e não recebe alvo genérico',()=>{const a=app(),p=pacote();p.itens[0].valor='< 140';preparar(a,p);aplicar(a);assert.equal(a.run('E.exames[0].valor'),'< 140');assert.equal(a.run('semaforo(E.exames[0])'),'')});
test('Documentos: peso vai à série existente com data e origem',()=>{const a=app();preparar(a,pacote('peso'));aplicar(a);assert.equal(a.run('E.peso[0].kg'),140.5);assert.equal(a.run('E.peso[0].data'),'2026-02-10');assert.equal(a.run('E.peso[0].origemDocumental.fonteId'),'fonte-1')});
test('Documentos: orientação histórica não cria tratamento ativo',()=>{const a=app();preparar(a,pacote('registroSaude'));aplicar(a);assert.equal(a.run('E.tratamentos.length'),0);assert.equal(a.run('E.acervoDocumental[0].registros.length'),1)});
test('Documentos: leitura entra para conferir e sem mudar personalidade anterior',()=>{const a=app();preparar(a,pacote('leitura'));const c=a.run('JSON.stringify(E.comportamento)');aplicar(a);assert.equal(a.run('devDados().leituras[0].status'),'A conferir');assert.equal(a.run('devDados().fontes.length'),1);assert.equal(a.run('devDados().leituras[0].fontes[0]===devDados().fontes[0].id'),true);assert.equal(a.run('JSON.stringify(E.comportamento)'),c);assert.equal(a.run('E.pdi.length'),0)});
test('Documentos: avaliação previamente cadastrada conserva ID e percepções',()=>{const a=app();preparar(a,pacote('leitura'));a.run('devDados().fontes=[{id:"original",url:"https://drive.google.com/file/d/fonte-1/view?usp=sharing",resumo:"Meu registro"}]');aplicar(a);assert.equal(a.run('devDados().fontes.length'),1);assert.equal(a.run('devDados().fontes[0].resumo'),'Meu registro');assert.equal(a.run('devDados().leituras[0].fontes[0]'),'original')});
test('Documentos: fonte sem leitura só admite referência',()=>{const a=app(),p=pacote();p.fontes[0].lido=false;assert.throws(()=>preparar(a,p),/fonte que foi lida/);p.itens=[];preparar(a,p);aplicar(a,['fonte:fonte-1']);assert.equal(a.run('E.acervoDocumental[0].lido'),false)});
test('Documentos: validade de estrutura, datas e links antes da mutação',()=>{const a=app();for(const alterar of [p=>p.itens[0].data='2026-02-31',p=>p.fontes[0].url='javascript:alert(1)',p=>p.itens[0].fonteId='ausente',p=>p.itens[0].tipo='sos',p=>p.fontes.push(p.fontes[0])]){const p=pacote();alterar(p);assert.throws(()=>preparar(a,p));}assert.equal(a.run('gravacoes'),0)});
test('Documentos: backup preserva fontes e reprova lista interna malformada',()=>{const a=app();preparar(a,pacote('registroSaude'));aplicar(a);assert.equal(a.run('validarBackup(structuredClone(E)).acervoDocumental[0].registros.length'),1);assert.throws(()=>a.run('validarBackup({...structuredClone(E),acervoDocumental:[{registros:"erro"}]})'),/acervoDocumental.registros/)});
test('Documentos: texto HTML da fonte é mostrado como texto',()=>{const a=app(),p=pacote();p.fontes[0].resumo='<img src=x onerror=alert(1)>';preparar(a,p);a.run('docMostrarRevisao(p)');assert.equal(a.document.querySelector('.doc-revisao img'),null);assert.match(a.document.querySelector('.doc-revisao').textContent,/<img/)});
test('Documentos: acervo de saúde abre fontes datadas com links',()=>{const a=app();preparar(a,pacote('registroSaude'));aplicar(a);a.run('docAbrirAcervo("saude")');assert.match(a.document.querySelector('.doc-acervo').textContent,/10\/02\/2026/);assert.equal(a.document.querySelector('.doc-acervo a').getAttribute('href'),'https://drive.google.com/file/d/fonte-1/view')});
test('Documentos: valores conflitantes entre fontes do mesmo pacote não são importados juntos',()=>{const a=app(),p=pacote();p.itens.push({...p.itens[0],id:'outra-leitura',valor:'150'});preparar(a,p);assert.equal(a.run('docPlano(p)[2].status'),'conflito');assert.throws(()=>aplicar(a,['fonte:fonte-1','item:item-1','item:outra-leitura']),/seleção mudou/);assert.equal(a.run('E.exames.length'),0)});
test('Documentos: seleção em lote é explícita e informa itens fora do filtro',()=>{const a=app();preparar(a);a.run('docMostrarRevisao(p)');[...a.document.querySelectorAll('button')].find(b=>b.textContent==='Selecionar novos visíveis').click();assert.match(a.document.querySelector('.doc-revisao [role=status]').textContent,/1 fonte\(s\) \+ 1 informação/);const busca=a.document.querySelector('.doc-revisao input[type=search]');busca.value='ausente';busca.oninput();assert.match(a.document.querySelector('.doc-revisao [role=status]').textContent,/2 selecionado\(s\) fora do filtro/);[...a.document.querySelectorAll('button')].find(b=>b.textContent==='Desmarcar tudo').click();assert.ok([...a.document.querySelectorAll('input[type=checkbox]')].every(x=>!x.checked));assert.equal(a.run('gravacoes'),0)});

test('Documentos: detalhe de exame documental mostra referência original sem alvo genérico',()=>{const a=app();preparar(a);aplicar(a);a.run('modalMarcador("LDL")');const texto=a.document.querySelector('#modais').textContent;assert.match(texto,/Referência do laudo/);assert.match(texto,/Intervalo do laudo/);assert.doesNotMatch(texto,/Alvo cadastrado/);assert.match(a.document.querySelector('#modais a').getAttribute('href'),/fonte-1/)});

test('Documentos: limites e data da interpretação acompanham a leitura guardada e visível',()=>{const a=app(),p=pacote('leitura');p.itens[0].limites='Interpretação sem instrumento clínico';preparar(a,p);aplicar(a);assert.equal(a.run('devDados().leituras[0].limites'),p.itens[0].limites);assert.equal(a.run('devDados().leituras[0].data'),'2026-02-10');a.run('devModalLeitura(devDados().leituras[0])');assert.match(a.document.querySelector('#modais').textContent,/Interpretação sem instrumento clínico/);assert.match(a.document.querySelector('#modais').textContent,/10\/02\/2026/)});
test('Documentos: registro documental pertence à versão selecionada da fonte',()=>{const a=app();preparar(a,pacote('registroSaude'));aplicar(a);const p=pacote('registroSaude');p.fontes[0].versao='2';p.itens[0].id='versao-2';p.itens[0].texto='Nova leitura';preparar(a,p);aplicar(a,['fonte:fonte-1','item:versao-2']);assert.equal(a.run('E.acervoDocumental[0].registros.length'),1);assert.equal(a.run('E.acervoDocumental[1].registros[0].texto'),'Nova leitura');assert.equal(a.run('E.acervoDocumental[1].registros[0].origemDocumental.versao'),'2')});
test('Documentos: identidade da fonte respeita domínio e links alternativos do Drive',()=>{const a=app();assert.notEqual(a.run('docFonteChave({url:"https://example.com/d/igual"})'),a.run('docFonteChave({url:"https://outro.com/d/igual"})'));assert.equal(a.run('docFonteChave({url:"https://drive.google.com/open?id=teste"})'),a.run('docFonteChave({url:"https://docs.google.com/document/d/teste/edit?usp=sharing"})'))});

test('Documentos: IDs normalizados não admitem duplicidade com espaços',()=>{const a=app();const p=pacote();p.fontes.push({...p.fontes[0],id:' fonte-1 '});assert.throws(()=>preparar(a,p),/repetida/);const q=pacote();q.itens.push({...q.itens[0],id:' item-1 '});assert.throws(()=>preparar(a,q),/repetidos/);const r=pacote();r.itens[0].fonteId=' fonte-1 ';preparar(a,r);assert.equal(a.run('p.itens[0].fonteId'),'fonte-1')});
test('Documentos: revisão completa fonte pendente sem substituir notas ou notas de avaliação',()=>{const a=app(),p=pacote('leitura');p.fontes[0].disc={natural:{D:60},adaptado:{D:50}};preparar(a,p);a.run('devDados().fontes=[{id:"anterior",url:p.fontes[0].url,pendente:true,revisado:false,resumo:"Minha anotação"}]');aplicar(a);assert.equal(a.run('devDados().fontes[0].resumo'),'Minha anotação');assert.equal(a.run('devDados().fontes[0].disc.natural.D'),60);assert.equal(a.run('devDados().fontes[0].pendente'),false);assert.equal(a.run('devDados().fontes[0].id'),'anterior');assert.equal(a.run('devDados().leituras[0].fontes[0]'),'anterior')});
test('Documentos: versão de avaliação existente é preservada enquanto acervo conserva nova leitura',()=>{const a=app(),p=pacote('leitura');p.fontes[0].disc={natural:{D:60},adaptado:{D:50}};preparar(a,p);a.run('devDados().fontes=[{id:"anterior",url:p.fontes[0].url,disc:{natural:{D:65}}}]');aplicar(a);assert.equal(a.run('devDados().fontes[0].disc.natural.D'),65);assert.equal(a.run('E.acervoDocumental[0].disc.natural.D'),60)});

test('Documentos: avaliações rejeitam estrutura e pontuações inválidas, medição rejeita objeto',()=>{const a=app();for(const altera of [p=>p.fontes[0].disc={natural:71,adaptado:38},p=>p.fontes[0].disc={natural:{D:101}},p=>p.fontes[0].lideranca={Executivo:999},p=>p.fontes[0].lideranca={Motivador:'forte'},p=>p.itens[0].valor={resultado:12}]){const p=pacote();altera(p);assert.throws(()=>preparar(a,p))}assert.equal(a.run('gravacoes'),0)});
test('Documentos: escores associados à fonte aparecem antes de qualquer confirmação',()=>{const a=app(),p=pacote('leitura');p.fontes[0].disc={natural:{D:60,I:50,S:40,C:30},adaptado:{D:40,I:30,S:20,C:10}};p.fontes[0].lideranca={Executivo:30,Metódico:20,Motivador:25,Sistemático:25};preparar(a,p);a.run('docMostrarRevisao(p)');const texto=a.document.querySelector('.doc-revisao-avaliacao').textContent;assert.match(texto,/Natural — D 60 · I 50 · S 40 · C 30/);assert.match(texto,/Executivo 30/);assert.equal(a.run('gravacoes'),0)});

test('Documentos: conflito entre protocolos não escolhe o primeiro como verdadeiro',()=>{const a=app(),p=pacote();p.itens.push({...p.itens[0],id:'segundo',valor:'150'});preparar(a,p);assert.equal(a.run('docPlano(p)[1].status'),'conflito');assert.equal(a.run('docPlano(p)[2].status'),'conflito');assert.throws(()=>aplicar(a),/seleção mudou/);assert.equal(a.run('gravacoes'),0)});
test('Documentos: unidade ausente no laudo não é inventada a partir do marcador',()=>{const a=app(),p=pacote();p.itens[0].unidade='';preparar(a,p);aplicar(a);assert.equal(a.run('unidadeSaude(E.exames[0])'),'')});
