import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/dom.mjs';
function app(){const a=setup();a.run("E=structuredClone(SEED);E.empresasPJ=[{id:'pj',nome:'Antiga'}];E.rendimentos=[{id:'r',empresa:'Antiga',valor:42}];E.bancos=[{id:'b',titular:'Antiga'}];E.obras=[{id:'o',empresa:'Antiga'}];E.marcas={Antiga:{cor:'#abc',encerradaEm:'2026-01-01'}};E.estrategia={Antiga:{missao:'Original',objetivos:[{id:'objetivo',titulo:'Meta',acoes:[{id:'acao',oque:'Conferir proposta',ate:'2027-03-01'}]}]}};E.planejamentoEmpresas=[];E.rendHist={empresas:{Antiga:[1,2,3]},detalhe:{2026:{Antiga:[{id:'det',valor:99}]}}};migrarPlanejamento(E)");return a}
test('Renomear empresa preserva origem migrada e não duplica eventos na Agenda',()=>{const {run}=app();run("const p=E.planejamentoEmpresas[0];const id=p.id;const empresaId=p.empresaId;const antes=planosParaAgenda().length;renomeiaEmpresa('Antiga','Nova')");assert.equal(run('antes'),1);assert.equal(run('planosParaAgenda().length'),1);assert.equal(run('p.origemLegado'),'Nova');assert.equal(run('p.id===id&&p.empresaId===empresaId'),true);assert.equal(run('migrarPlanejamento(E)'),false);assert.equal(run('E.planejamentoEmpresas.length'),1)});
test('Renomear reconecta empresa, banco, obra, lançamentos e histórico sem alterar valores',()=>{const {run}=app();run("renomeiaEmpresa('Antiga','Nova')");for(const expressao of ['E.empresasPJ[0].nome','E.bancos[0].titular','E.obras[0].empresa','E.rendimentos[0].empresa','E.planejamentoEmpresas[0].empresaNome'])assert.equal(run(expressao),'Nova');assert.equal(run('E.rendimentos[0].valor'),42);assert.equal(run('E.rendHist.detalhe[2026].Nova[0].valor'),99);assert.equal(run('JSON.stringify(E.rendHist.empresas.Nova)'),'[1,2,3]');assert.equal(run('E.marcas.Nova.encerradaEm'),'2026-01-01');assert.equal(run('contasDaEmpresa(E.empresasPJ[0]).length'),1)});
test('Ficha Empresas usa a mesma rotina e devolve nome normalizado',()=>{const a=app();a.run("empresaSalvarFicha(E.empresasPJ[0],false,{...E.empresasPJ[0],nome:'   Nova   '},{nome:'   Nova   '})");assert.equal(a.run('E.empresasPJ[0].nome'),'Nova');assert.equal(a.run('E.rendimentos[0].empresa'),'Nova');assert.equal(a.run('E.planejamentoEmpresas[0].origemLegado'),'Nova');assert.equal(a.run('planosParaAgenda().length'),1)});
test('Nova ficha só renomeia ou grava ao salvar, nunca durante preenchimento',()=>{const a=app();a.run("const antes=JSON.stringify(E);empresaModalFicha()");const input=a.document.querySelector('[name=nome]');input.value='Rascunho';input.dispatchEvent(new a.document.defaultView.Event('input'));assert.equal(a.run('JSON.stringify(E)===antes'),true);a.document.querySelector('.ff-actions button[type=button]').click();assert.equal(a.run('JSON.stringify(E)===antes'),true)});
test('Empresa de outro destino bloqueia junção e preserva os dois históricos',()=>{const {run}=app();run("E.empresasPJ.push({id:'outra',nome:'Outra'});E.estrategia.Outra={missao:'Não sobrescrever'};const antes=JSON.stringify(E);const mudou=renomeiaEmpresa('Antiga','Outra')");assert.equal(run('mudou'),false);assert.equal(run('JSON.stringify(E)===antes'),true)});
test('Conflito de destino ignora caixa e acentos para não criar nomes ambíguos',()=>{const {run}=app();run("E.empresasPJ.push({id:'outra',nome:'Empresa Ágil'});const antes=JSON.stringify(E);const mudou=renomeiaEmpresa('Antiga','empresa agil')");assert.equal(run('mudou'),false);assert.equal(run('JSON.stringify(E)===antes'),true)});
test('Destino só no detalhe histórico também é protegido contra sobrescrita',()=>{const {run}=app();run("E.rendHist.detalhe[2025]={Outra:[{valor:333}]};const antes=JSON.stringify(E);const mudou=renomeiaEmpresa('Antiga','Outra')");assert.equal(run('mudou'),false);assert.equal(run('JSON.stringify(E)===antes'),true)});
test('Configurações restaura campo quando a renomeação é rejeitada',async()=>{const {run,document}=app();run("E.empresasPJ.push({id:'outra',nome:'Outra'});atual='config'");await run("vConfig(document.getElementById('main'))");const input=[...document.querySelectorAll('.bNome')].find(x=>x.value==='Antiga');input.value='Outra';input.onchange();assert.equal(input.value,'Antiga');assert.equal(run('E.empresasPJ[0].nome'),'Antiga')});
test('Configurações chama helper global preservando os IDs e a Agenda',async()=>{const {run,document}=app();run("atual='config'");await run("vConfig(document.getElementById('main'))");const input=[...document.querySelectorAll('.bNome')].find(x=>x.value==='Antiga');input.value='Nova';input.onchange();assert.equal(run('E.planejamentoEmpresas[0].empresaId'),'pj');assert.equal(run('E.planejamentoEmpresas[0].origemLegado'),'Nova');assert.equal(run('planosParaAgenda().length'),1)});
test('Plano só vinculado por ID recebe nome atual sem modificar resultados',()=>{const {run}=app();run("const p=E.planejamentoEmpresas[0];delete p.empresaNome;p.objetivos[0].historicoResultados=[{resultado:'Original',resultadoEm:''}];const antes=JSON.stringify(p.objetivos);renomeiaEmpresa('Antiga','Nova')");assert.equal(run('p.empresaNome'),'Nova');assert.equal(run('JSON.stringify(p.objetivos)===antes'),true)});
test('Completar ficha antiga sem nome não altera campos vazios de outras coleções',()=>{const {run}=app();run("E.empresasPJ.push({id:'sem',nome:''});E.bancos.push({id:'vazio',titular:''});const ficha=E.empresasPJ[1];renomeiaEmpresa('','Empresa nova',ficha)");assert.equal(run('ficha.nome'),'Empresa nova');assert.equal(run('E.bancos[1].titular'),'');assert.equal(run('E.empresasPJ[0].nome'),'Antiga')});
test('Vínculo contraditório por ID bloqueia renomeação sem adivinhar a empresa',()=>{const {run}=app();run("E.empresasPJ.push({id:'outra',nome:'Outra'});E.bancos.push({id:'conflito',empresaId:'outra',titular:'Antiga'});const antes=JSON.stringify(E);const mudou=renomeiaEmpresa('Antiga','Nova')");assert.equal(run('mudou'),false);assert.equal(run('JSON.stringify(E)===antes'),true)});
test('Fichas duplicadas com mesmo nome precisam ser conferidas antes de renomear',()=>{const {run}=app();run("E.empresasPJ.push({id:'duplicada',nome:'Antiga'});const antes=JSON.stringify(E);const mudou=renomeiaEmpresa('Antiga','Nova')");assert.equal(run('mudou'),false);assert.equal(run('JSON.stringify(E)===antes'),true)});
