import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/dom.mjs';
function app(){const a=setup();a.run("E=structuredClone(SEED);E.empresasPJ=[{id:'pj-b',nome:'Beta',cnpj:'',status:'Ativa',documentosEmpresa:[],obrigacoesEmpresa:[]},{id:'pj-a',nome:'Ágata',cidade:'Montes Claros',documentosEmpresa:[],obrigacoesEmpresa:[]}];E.bancos=[{id:'b',banco:'Banco teste',titular:'Beta',conta:'123'}];E.patrimonio=[{id:'im',nome:'Imóvel de teste',tipo:'Imóvel',empresaId:'pj-b',onde:'Rua teste'},{id:'livre',nome:'Imóvel livre',tipo:'Imóvel'},{id:'outro',nome:'Imóvel de outra empresa',empresaId:'pj-a'}];E.rendimentos=[{id:'r',empresa:'Beta',valor:42,data:'2027-01-01'}];E.planejamentoEmpresas=[];E.estrategia={};atual='empresas';globalThis.emp=E.empresasPJ[0];");return a}
function submit(a,values){const form=a.document.querySelector('#modais .fundo:last-child form');for(const [k,v] of Object.entries(values))form.querySelector(`[name=${k}]`).value=String(v);form.onsubmit({preventDefault(){}});return form}
function snap(a){return a.run('JSON.stringify(E)')}
function doc(a){a.run("emp.documentosEmpresa=[{id:'doc',nome:'Contrato inicial',tipo:'Contrato social',data:'2026-01-02',validade:'2027-02-01',status:'Vigente',url:'https://drive.google.com/file/d/exemplo/view',obs:'Texto original'}]")}
function obrig(a){a.run("emp.obrigacoesEmpresa=[{id:'iptu',nome:'IPTU parcela 1',tipo:'IPTU',ano:'2027',patrimonioId:'im',vencimento:'2027-02-10',valor:125,status:'Pendente'}]")}
test('Empresas em ordem alfabética e busca por nome/cidade sem mutar cadastros',()=>{const a=app(),antes=snap(a);assert.equal(a.run("empresaLista().map(e=>e.nome).join(',')"),'Ágata,Beta');assert.equal(a.run("empresaLista('montes clar').length"),1);assert.equal(a.run("empresaLista('agat')[0].id"),'pj-a');assert.equal(snap(a),antes)});
test('Menu tem Empresas no grupo Empresa; ficha conserva todas as seções visíveis',()=>{const a=app();a.run("filtro.empresaId='pj-b';menu();tela()");assert.equal(a.run("MODS.find(m=>m.id==='empresas').grupo"),'Empresa');for(const id of ['gerais','bancos','documentos','imoveis','conexoes'])assert.ok(a.document.querySelector('#empresa-'+id));assert.equal(a.document.querySelectorAll('.empresa-ficha details').length,0);assert.equal(a.document.querySelectorAll('.empresa-opcao').length,2)});
test('Atalho antigo gu-empresas e busca da PJ abrem a ficha empresarial correta',()=>{const a=app();a.run("abreBloco('gu-empresas');irTela('guia')");assert.equal(a.run('atual'),'empresas');a.run("abrirRegistro('guia','empresasPJ',emp)");assert.equal(a.run('filtro.empresaId'),'pj-b');assert.equal(a.run('atual'),'empresas')});
for(const [nome,abrir] of [['empresa','empresaModalFicha()'],['banco','empresaModalBanco(emp)'],['documento','empresaModalDocumento(emp)'],['obrigação','empresaModalObrigacao(emp)']])test(`Cancelar novo ${nome} não cria registro nem muda versão`,()=>{const a=app(),antes=snap(a);a.run(abrir);const inp=a.document.querySelector('form input');inp.value='Rascunho';inp.dispatchEvent(new a.document.defaultView.Event('input'));a.document.querySelector('.ff-actions button[type=button]').click();assert.equal(snap(a),antes)});
test('Salvar empresa por formulário cria ID único e mesma base E.empresasPJ',()=>{const a=app();a.run('empresaModalFicha()');submit(a,{nome:'  Nova Empresa  ',cnpj:'11.222.333/0001-81',cidade:'Cidade teste'});assert.equal(a.document.querySelector('.ff-error')?.textContent||'','');assert.equal(a.run('E.empresasPJ.length'),3);assert.equal(a.run('E.empresasPJ[2].nome'),'Nova Empresa');assert.ok(a.run('E.empresasPJ[2].id'));assert.equal(a.run('E.empresasPJ[2].documentosEmpresa.length'),0)});
test('CNPJ inválido, duplicado e nome ambíguo não geram cadastro',()=>{const a=app();a.run("globalThis.n={id:'nova'}");const antes=snap(a);for(const v of [{nome:'Nova',cnpj:'11.111.111/1111-11'},{nome:'agata',cnpj:''}])assert.throws(()=>a.run('empresaSalvarFicha(n,true,'+JSON.stringify(v)+')'));assert.equal(snap(a),antes);a.run("emp.cnpj='11.222.333/0001-81'");assert.throws(()=>a.run("empresaSalvarFicha(n,true,{nome:'Outra',cnpj:'11222333000181'})"));});
test('Edição da empresa renomeia vínculos, preserva IDs e histórico empresarial',()=>{const a=app();doc(a);obrig(a);a.run("E.estrategia.Beta={missao:'Original',objetivos:[{id:'ob',titulo:'Meta',acoes:[{id:'acao',ate:'2027-02-01'}]}]};migrarPlanejamento(E);globalThis.docRef=empresaRefArquivo(emp,emp.documentosEmpresa[0]);globalThis.hist=JSON.stringify(emp.documentosEmpresa);empresaSalvarFicha(emp,false,{...emp,nome:'Nova Beta'},{nome:'Nova Beta'})");assert.equal(a.run('emp.id'),'pj-b');assert.equal(a.run('E.bancos[0].titular'),'Nova Beta');assert.equal(a.run('E.rendimentos[0].empresa'),'Nova Beta');assert.equal(a.run('E.rendimentos[0].valor'),42);assert.equal(a.run('planosParaAgenda().length'),1);assert.equal(a.run('E.planejamentoEmpresas[0].origemLegado'),'Nova Beta');assert.equal(a.run('empresaRefArquivo(emp,emp.documentosEmpresa[0])===docRef'),true);assert.equal(a.run('JSON.stringify(emp.documentosEmpresa)===hist'),true)});
test('Formulário rejeita renomeação para cadastro existente e mantém todos os dados',()=>{const a=app();a.run('empresaModalFicha(emp)');const antes=snap(a);submit(a,{nome:'Ágata'});assert.match(a.document.querySelector('.ff-error').textContent,/existe/);assert.equal(snap(a),antes)});
test('Cancelamento de documento editado preserva texto e não cria revisão',()=>{const a=app();doc(a);const antes=snap(a);a.run('empresaModalDocumento(emp,emp.documentosEmpresa[0])');const input=a.document.querySelector('[name=obs]');input.value='Texto rascunho';input.dispatchEvent(new a.document.defaultView.Event('input'));a.document.querySelector('.ff-actions button[type=button]').click();assert.equal(snap(a),antes)});
test('Editar documento guarda revisão anterior completa; salvar sem alteração não duplica',()=>{const a=app();doc(a);a.run("const d=emp.documentosEmpresa[0];empresaSalvarInterno(emp,'documentosEmpresa',d,false,{...d,obs:'Novo texto'},{obs:'Novo texto'});empresaSalvarInterno(emp,'documentosEmpresa',d,false,{...d},{})");assert.equal(a.run('emp.documentosEmpresa[0].revisoes.length'),1);assert.equal(a.run('emp.documentosEmpresa[0].revisoes[0].obs'),'Texto original');assert.equal(a.run('emp.documentosEmpresa[0].revisoes[0].data'),'2026-01-02');assert.equal(a.run('emp.documentosEmpresa[0].revisoes[0].url'),'https://drive.google.com/file/d/exemplo/view');a.run('empresaModalDocumento(emp,emp.documentosEmpresa[0])');assert.match(a.document.querySelector('.empresa-historico').textContent,/Texto original/)});
test('Datas impossíveis, validade anterior e link perigoso são rejeitados sem mutação',()=>{const a=app();doc(a);const antes=snap(a);for(const patch of [{data:'2027-02-30'},{validade:'2025-01-01'},{url:'javascript:alert(1)'},{url:'https://user:senha@example.com/'}])assert.throws(()=>a.run("empresaSalvarInterno(emp,'documentosEmpresa',emp.documentosEmpresa[0],false,{...emp.documentosEmpresa[0],..."+JSON.stringify(patch)+'},'+JSON.stringify(patch)+')'));assert.equal(snap(a),antes)});
test('Documentos anteriores precisam da mesma empresa e não podem formar ciclo',()=>{const a=app();doc(a);a.run("emp.documentosEmpresa.push({id:'alt',nome:'Alteração',anteriorId:'doc'});E.empresasPJ[1].documentosEmpresa=[{id:'externo',nome:'Outro contrato'}]");const antes=snap(a);for(const id of ['alt','doc','externo'])assert.throws(()=>a.run("empresaSalvarInterno(emp,'documentosEmpresa',emp.documentosEmpresa[0],false,{...emp.documentosEmpresa[0],anteriorId:'"+id+"'},{anteriorId:'"+id+"'})"));assert.equal(snap(a),antes)});
test('IPTU exige imóvel por ID desta empresa, ano e vencimento válidos',()=>{const a=app();const antes=snap(a);for(const patch of [{patrimonioId:''},{patrimonioId:'outro'},{patrimonioId:'inexistente'},{ano:'20'},{vencimento:'2027-02-30'},{valor:'-1'}])assert.throws(()=>a.run("empresaSalvarInterno(emp,'obrigacoesEmpresa',{id:'novo'},true,{nome:'IPTU',tipo:'IPTU',ano:'2027',vencimento:'2027-02-01',valor:'',status:'Pendente',patrimonioId:'im',..."+JSON.stringify(patch)+'})'));assert.equal(snap(a),antes)});
test('IPTU aceita valor brasileiro, mantém ano manual e não infere pagamento vencido',()=>{const a=app();a.run("empresaSalvarInterno(emp,'obrigacoesEmpresa',{id:'novo'},true,{nome:'IPTU antigo',tipo:'IPTU',ano:'2025',vencimento:'2025-02-01',valor:'1.234,56',status:'Pendente',patrimonioId:'im'})");assert.equal(a.run('emp.obrigacoesEmpresa[0].valor'),1234.56);assert.equal(a.run('emp.obrigacoesEmpresa[0].ano'),'2025');assert.equal(a.run('emp.obrigacoesEmpresa[0].status'),'Pendente');assert.equal(a.run('empresaEventos().length'),1)});
test('Valor desconhecido permanece vazio e pagamento futuro é recusado',()=>{const a=app();a.run("empresaSalvarInterno(emp,'obrigacoesEmpresa',{id:'novo'},true,{nome:'Taxa',tipo:'Taxa',ano:'2027',vencimento:'2027-02-01',valor:'',status:'A conferir'})");assert.equal(a.run('emp.obrigacoesEmpresa[0].valor'),'');const antes=snap(a);assert.throws(()=>a.run("empresaSalvarInterno(emp,'obrigacoesEmpresa',emp.obrigacoesEmpresa[0],false,{...emp.obrigacoesEmpresa[0],status:'Pago',pagoEm:'2200-01-01'},{status:'Pago',pagoEm:'2200-01-01'})"));assert.equal(snap(a),antes)});
test('Agenda deriva vencimentos com IDs estáveis sem criar cópias E.agenda',()=>{const a=app();doc(a);obrig(a);const antes=snap(a);assert.equal(a.run('empresaEventos().length'),2);assert.equal(a.run("JSON.stringify(empresaEventos().map(e=>e.id))"),a.run("JSON.stringify(empresaEventos().map(e=>e.id))"));assert.equal(a.run("eventosDoEcossistema().filter(e=>e.fonte==='empresas').length"),2);assert.equal(a.run("eventosDoEcossistema().filter(e=>e.fonte==='empresas').length"),2);assert.equal(a.run('E.agenda.length'),0);assert.equal(snap(a),antes)});
test('Pago e Histórico saem dos vencimentos sem apagar histórico e voltam ao reabrir',()=>{const a=app();doc(a);obrig(a);a.run("emp.documentosEmpresa[0].status='Histórico';empresaSalvarInterno(emp,'obrigacoesEmpresa',emp.obrigacoesEmpresa[0],false,{...emp.obrigacoesEmpresa[0],status:'Pago'},{status:'Pago'})");assert.equal(a.run('empresaEventos().length'),0);assert.equal(a.run('emp.obrigacoesEmpresa[0].revisoes[0].status'),'Pendente');a.run("empresaSalvarInterno(emp,'obrigacoesEmpresa',emp.obrigacoesEmpresa[0],false,{...emp.obrigacoesEmpresa[0],status:'Pendente'},{status:'Pendente'})");assert.equal(a.run('empresaEventos().length'),1);assert.equal(a.run('emp.obrigacoesEmpresa.length'),1)});
test('Evento empresarial abre o item na ficha correta; datas alteradas refletem na Agenda',()=>{const a=app();obrig(a);a.run("emp.obrigacoesEmpresa[0].vencimento='2027-03-04';abrirEventoCentral(empresaEventos()[0])");assert.equal(a.run('atual'),'empresas');assert.equal(a.run('filtro.empresaId'),'pj-b');assert.equal(a.document.querySelector('[name=vencimento]').value,'2027-03-04')});
test('Filtro da Agenda por empresa e retorno a todas preservam acesso aos eventos',()=>{const a=app();obrig(a);a.run("E.empresasPJ[1].obrigacoesEmpresa=[{id:'b2',nome:'Outra obrigação',vencimento:'2027-02-11',status:'Pendente'}];filtro.agEmpresaId='pj-b';filtro.agSo='empresas';filtro.agMes='2027-02';atual='agenda';tela()");assert.match(a.document.querySelector('.empresa-agenda-contexto').textContent,/Beta/);a.document.querySelector('.empresa-agenda-contexto button').click();assert.equal(a.run('filtro.agEmpresaId'),'');assert.equal(a.run('empresaEventos().length'),2)});
test('Busca encontra dados gerais, documentos, revisões e IPTU pelo imóvel',()=>{const a=app();doc(a);obrig(a);a.run("emp.contato='Responsável exclusivo';emp.documentosEmpresa[0].revisoes=[{obs:'Ata preservada exclusiva'}]");for(const q of ['responsavel exclusivo','contrato inicial','ata preservada','iptu imóvel de teste'])assert.ok(a.run('buscarEmTudo('+JSON.stringify(q)+').length')>0);a.run("buscarEmTudo('ata preservada')[0].abrir()");assert.equal(a.run('filtro.empresaId'),'pj-b');assert.ok(a.document.querySelector('[name=nome]'))});
test('Banco vinculado por ID continua único após renomeação e edição da conta',()=>{const a=app();a.run("empresaSalvarBanco(emp,E.bancos[0],false,{...E.bancos[0],agencia:'0001'},{agencia:'0001'});renomeiaEmpresa('Beta','Beta nova')");assert.equal(a.run('E.bancos.length'),1);assert.equal(a.run('E.bancos[0].empresaId'),'pj-b');assert.equal(a.run('empresaContas(emp).length'),1);assert.equal(a.run('E.bancos[0].conta'),'123');assert.equal(a.run('E.bancos[0].agencia'),'0001')});
test('Titular de banco com vínculo explícito não se troca pela tabela antiga',()=>{const a=app();a.run("E.bancos[0].empresaId='pj-b';atual='guia';filtro.guiaAba='cadastros';tela()");const input=a.document.querySelector('[data-bid=gu-bancos] input[data-k=titular]');input.value='Outra pessoa';input.dispatchEvent(new a.document.defaultView.Event('change',{bubbles:true}));assert.equal(a.run('E.bancos[0].titular'),'Beta');assert.equal(input.value,'Beta')});
test('Nova conta duplicada é rejeitada e banco de outra empresa não é reassociado',()=>{const a=app();const antes=snap(a);assert.throws(()=>a.run("empresaSalvarBanco(emp,{id:'novo'},true,{banco:'Banco teste',conta:'123'})"));a.run("E.bancos.push({id:'outro',banco:'Outro',empresaId:'pj-a',titular:'Ágata'})");assert.throws(()=>a.run("empresaVincularRegistro(emp,'bancos','outro')"));assert.equal(a.run('E.bancos.length'),2);assert.equal(a.run('E.bancos[1].empresaId'),'pj-a');assert.ok(antes)});
test('Nome duplicado não atribui conta ambígua; ID explícito prevalece',()=>{const a=app();a.run("E.empresasPJ.push({id:'dupla',nome:'Beta'});E.bancos.push({id:'exp',empresaId:'pj-b',banco:'Explícito',titular:'Nome antigo'})");assert.equal(a.run("empresaContas(emp).map(b=>b.id).join(',')"),'exp')});
test('Vincular imóvel grava ID no patrimônio sem cadastro paralelo nem alteração de valores',()=>{const a=app();a.run("E.patrimonio[1].valor=999;empresaVincularRegistro(emp,'patrimonio','livre');empresaVincularRegistro(emp,'patrimonio','livre')");assert.equal(a.run('E.patrimonio.length'),3);assert.equal(a.run('E.patrimonio[1].empresaId'),'pj-b');assert.equal(a.run('E.patrimonio[1].valor'),999);assert.equal(a.run('empresaRegistros(emp,"patrimonio").length'),2);assert.throws(()=>a.run("empresaVincularRegistro(emp,'patrimonio','outro')"))});
test('Referência de imóvel ausente permanece visível e backup recuperável',()=>{const a=app();obrig(a);a.run("E.patrimonio=[];filtro.empresaId=emp.id;tela()");assert.match(a.document.querySelector('#empresa-imoveis').textContent,/Imóvel não encontrado/);assert.equal(a.run('validarBackup(structuredClone(E)).empresasPJ[0].obrigacoesEmpresa[0].patrimonioId'),'im')});
test('Backup valida documentos, obrigações e histórico e recusa tipos/IDs inválidos',()=>{const a=app();doc(a);obrig(a);assert.equal(a.run('validarBackup(structuredClone(E)).empresasPJ[0].documentosEmpresa[0].id'),'doc');for(const mutation of ["j.empresasPJ[0].documentosEmpresa={}","j.empresasPJ[0].obrigacoesEmpresa=[null]","j.empresasPJ[0].documentosEmpresa[0].revisoes={}","j.empresasPJ[0].documentosEmpresa.push({...j.empresasPJ[0].documentosEmpresa[0]})","j.empresasPJ.push({...j.empresasPJ[0]})"])assert.throws(()=>a.run('(()=>{const j=structuredClone(E);'+mutation+';validarBackup(j)})()'))});
test('Restauração e normalização preservam IDs, anexos, revisões e vínculos sem duplicar',()=>{const a=app();doc(a);obrig(a);a.run("emp.documentosEmpresa[0].revisoes=[{obs:'Anterior'}];globalThis.j=structuredClone(E);localStorage.getItem=()=>JSON.stringify(j);E=carregar();normalizarEmpresas(E);normalizarEmpresas(E)");assert.equal(a.run('E.empresasPJ.length'),2);assert.equal(a.run('E.empresasPJ[0].documentosEmpresa.length'),1);assert.equal(a.run('empresaRefArquivo(E.empresasPJ[0],E.empresasPJ[0].documentosEmpresa[0])'),'empresa:pj-b:documento:doc');assert.equal(a.run('E.empresasPJ[0].documentosEmpresa[0].revisoes[0].obs'),'Anterior');assert.equal(a.run('E.empresasPJ[0].obrigacoesEmpresa[0].patrimonioId'),'im')});
test('Backup anterior sem novas listas ganha somente estrutura vazia sem substituir a PJ',()=>{const a=app();a.run("delete emp.documentosEmpresa;delete emp.obrigacoesEmpresa;const id=emp.id;normalizarEmpresas(E)");assert.equal(a.run('emp.id===id'),true);assert.equal(a.run('emp.documentosEmpresa.length'),0);assert.equal(a.run('emp.obrigacoesEmpresa.length'),0)});
test('Caixa/VGV expõe consulta com fonte e aviso sem criar vínculos por nome parecido',()=>{const a=app();a.run("E.contas=[{id:'cx',empresaId:'pj-b',nome:'Caixa explícito'},{id:'parecido',nome:'Beta investimentos'}];filtro.empresaId='pj-b';tela()");assert.equal(a.run("empresaRegistros(emp,'contas').length"),1);assert.match(a.document.querySelector('#empresa-conexoes').textContent,/nova importação substitui/);assert.equal(a.run('E.contas[1].empresaId'),undefined)});

test('CNPJ numérico e alfanumérico seguem exemplo técnico da Receita sem remover letras',()=>{const a=app();for(const v of ['11.222.333/0001-81','12.ABC.345/01DE-35','12.abc.345/01de-35'])assert.equal(a.run('empresaCnpjValido('+JSON.stringify(v)+')'),true);for(const v of ['12.ABC.345/01DE-30','!!!','00.000.000/0000-00','12.ABC.345/01DE-XX'])assert.equal(a.run('empresaCnpjValido('+JSON.stringify(v)+')'),false);a.run("empresaSalvarFicha({id:'alfa'},true,{nome:'Exemplo alfanumérico',cnpj:'12.ABC.345/01DE-35'})");assert.equal(a.run('E.empresasPJ[2].cnpj'),'12.ABC.345/01DE-35');assert.throws(()=>a.run("empresaSalvarFicha({id:'duplicado'},true,{nome:'Outro exemplo',cnpj:'12abc34501de35'})"));});

test('Documentos e comprovantes de obrigações têm referências de anexos distintas e estáveis',()=>{const a=app();assert.notEqual(a.run("empresaRefArquivo(emp,{id:'mesmo'})"),a.run("empresaRefObrigacao(emp,{id:'mesmo'})"));a.run("const ref=empresaRefObrigacao(emp,{id:'o'});renomeiaEmpresa('Beta','Novo nome')");assert.equal(a.run("empresaRefObrigacao(emp,{id:'o'})===ref"),true)});

test('Novo planejamento anual abre o formulário preservando anos e resultados existentes',()=>{const a=app();a.run("E.planejamentoEmpresas=[{id:'pl',empresaId:emp.id,empresaNome:emp.nome,ano:2027,objetivos:[{id:'obj',resultado:'Preservado',acoes:[]}]}];normalizarPlano(E.planejamentoEmpresas[0]);filtro.empresaId=emp.id;tela()");const antes=a.run('JSON.stringify(E.planejamentoEmpresas)');[...a.document.querySelectorAll('button')].find(b=>b.textContent==='Novo planejamento anual').click();assert.equal(a.document.querySelector('[name=ano]').value,'2028');assert.equal(a.run('JSON.stringify(E.planejamentoEmpresas)'),antes);assert.match(a.document.querySelector('#modais').textContent,/Novo planejamento/)});
