import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/dom.mjs';
function app(){const a=setup();a.run("tela=()=>{};E.rendimentos=[];E.gastos=[];E.patrimonio=[];E.rendHist={anos:[],totalAno:[],empresas:{}};");return a}
function form(document){return document.querySelector('.ff-form')}
function fill(f,k,v){const c=f.querySelector('[name="'+k+'"]');assert.ok(c,'campo '+k);c.value=v;if(c.tagName==='SELECT'){const o=[...c.options].find(o=>o.value===v);if(o)o.selected=true}}
function submit(f){f.onsubmit({preventDefault(){}})}
function mount(run,fn){run(`var pagina=document.createElement('main');document.body.appendChild(pagina);${fn}(pagina)`)}
test('Rendimento novo fica fora dos totais até salvar; cancelar não deixa linha vazia',()=>{const {run,document}=app();run("modalRendimento({id:'novo',data:'2026-09-12',empresa:'Aplicação',valor:0},true)");assert.equal(run('E.rendimentos.length'),0);fill(form(document),'valor','500');assert.equal(run('E.rendimentos.length'),0);form(document).querySelector('[type=button]').onclick();assert.equal(run('E.rendimentos.length'),0)});
test('Salvar rendimento aceita moeda brasileira, preserva empresa e não persiste controle do rascunho',()=>{const {run,document}=app();run("modalRendimento({id:'novo',data:'2026-09-12',empresa:'Aplicação',valor:0},true)");fill(form(document),'valor','R$ 1.250,50');fill(form(document),'instituicao','Banco teste');submit(form(document));assert.equal(run('E.rendimentos.length'),1);assert.equal(run('E.rendimentos[0].valor'),1250.5);assert.equal(run('E.rendimentos[0].empresa'),'Aplicação');assert.equal(run("Object.hasOwn(E.rendimentos[0],'_ffNovo')"),false)});
test('Rendimento: rejeita valor inválido e data inexistente antes de gravar',()=>{const {run,document}=app();run("modalRendimento({id:'novo',data:'2026-02-30',empresa:'Aplicação',valor:0},true)");fill(form(document),'valor','10');submit(form(document));assert.equal(run('E.rendimentos.length'),0);assert.match(form(document).querySelector('[role=alert]').textContent,/data/);fill(form(document),'data','2026-02-28');fill(form(document),'valor','100abc');submit(form(document));assert.equal(run('E.rendimentos.length'),0);assert.match(form(document).querySelector('[role=alert]').textContent,/numérico/)});
test('Editar campo alterado por outra sessão não sobrescreve atualização concorrente',()=>{const {run,document}=app();run("E.rendimentos=[{id:'r',data:'2026-09-12',empresa:'Aplicação',valor:10,tipo:'Lucro'}];modalRendimento(E.rendimentos[0]);E.rendimentos[0].valor=90");fill(form(document),'valor','20');submit(form(document));assert.equal(run('E.rendimentos[0].valor'),90);assert.match(form(document).querySelector('[role=alert]').textContent,/mudou/)});
test('Editar uma observação preserva atualização concorrente em campo não editado',()=>{const {run,document}=app();run("E.rendimentos=[{id:'r',data:'2026-09-12',empresa:'Aplicação',valor:10,tipo:'Lucro'}];modalRendimento(E.rendimentos[0]);E.rendimentos[0].valor=90");fill(form(document),'obs','Conferido');submit(form(document));assert.equal(run('E.rendimentos[0].valor'),90);assert.equal(run('E.rendimentos[0].obs'),'Conferido')});
test('Todos os anos mostra todos os lançamentos e busca encontra o ano antigo',()=>{const {run,document}=app();run("E.rendimentos=[{id:'antigo',data:'2024-03-12',empresa:'Aplicação',valor:20,tipo:'Dividendos'},{id:'novo',data:'2026-09-12',empresa:'Aplicação',valor:80,tipo:'Lucro'}];filtro.rendAno='todos'");mount(run,'vRendimentos');const bloco=document.querySelector('[data-bid=rd-lanc]');assert.match(bloco.querySelector('h2').textContent,/todos os anos/);assert.equal(bloco.querySelectorAll('[data-ff-rend]').length,2);const inp=bloco.querySelector('input[type=search]');inp.value='dividendos';inp.oninput();assert.equal(bloco.querySelector('[data-ff-rend=antigo]').hidden,false);assert.equal(bloco.querySelector('[data-ff-rend=novo]').hidden,true);assert.match(bloco.querySelector('[role=status]').textContent,/1 de 2/);assert.match(bloco.querySelector('[role=status]').textContent,/20,00/)});
test('Histórico sem empresas não quebra a tela',()=>{const {run}=app();run("E.rendHist={anos:[2024],totalAno:[0],empresas:{}};filtro.rendAno=2024");assert.doesNotThrow(()=>mount(run,'vRendimentos'))});
test('Rendimentos vazios permite começar por Novo rendimento',()=>{const {run,document}=app();mount(run,'vRendimentos');assert.ok([...document.querySelectorAll('button')].some(b=>b.textContent==='+ Novo rendimento'))});
test('Bem novo exige nome, salva data da avaliação e mantém histórico vendido',()=>{const {run,document}=app();run("E.patrimonio=[{id:'historico',nome:'Vendido',situacao:'Vendido',valor:500,falta:0}];modalBem({id:'bem',nome:'',tipo:'Imóvel',valor:100,falta:20,situacao:'Financiado'},true)");submit(form(document));assert.equal(run('E.patrimonio.length'),1);fill(form(document),'nome','Apartamento');fill(form(document),'avaliadoEm','2026-09-12');submit(form(document));assert.equal(run('E.patrimonio.length'),2);assert.equal(run('E.patrimonio[1].avaliadoEm'),'2026-09-12');assert.equal(run('E.patrimonio[0].situacao'),'Vendido')});
test('Patrimônio Em carteira exibe somente bens atuais sem excluir histórico',()=>{const {run,document}=app();run("E.patrimonio=[{id:'a',nome:'Atual',situacao:'Quitado',valor:100,falta:0},{id:'v',nome:'Antigo',situacao:'Vendido',valor:500,falta:0}];filtro.ffBemSituacao='Em carteira'");mount(run,'vPatrimonio');assert.match(document.querySelector('[data-bid=pt-lista]').textContent,/Atual/);assert.doesNotMatch(document.querySelector('[data-bid=pt-lista]').textContent,/Antigo/);assert.equal(run('E.patrimonio.length'),2);assert.match(document.querySelector('.ff-patrimonio [role=status]').textContent,/1 de 2/)});
test('Novo gasto sem mês válido não grava; estorno válido permanece negativo',()=>{const {run,document}=app();run("modalLancamentoGasto({id:'g',mes:'2026-13',classe:'Casa',oque:'Estorno',valor:-20},true)");submit(form(document));assert.equal(run('E.gastos.length'),0);fill(form(document),'mes','2026-09');submit(form(document));assert.equal(run('E.gastos[0].valor'),-20)});
test('Repetir gastos inicia desmarcado e grava exatamente a seleção',()=>{const {run,document}=app();run("E.gastos=[{id:'a',mes:'2026-08',oque:'Mercado',valor:120,classe:'Casa'},{id:'b',mes:'2026-08',oque:'Consulta',valor:300,classe:'Saúde'}];financeiroRepetirGastos(E.gastos.slice(),'2026-09')");const itens=document.querySelectorAll('.ff-repeat-row input');const btn=[...document.querySelectorAll('button')].find(x=>x.textContent==='Adicionar selecionados');assert.equal(btn.disabled,true);itens[1].checked=true;itens[1].onchange({target:itens[1]});assert.match(document.querySelector('.mcorpo [role=status]').textContent,/1 selecionados/);btn.onclick();assert.equal(run('E.gastos.length'),3);assert.equal(run("E.gastos.filter(x=>x.mes==='2026-09')[0].oque"),'Consulta');assert.equal(run("E.gastos.filter(x=>x.mes==='2026-08').length"),2)});
test('Busca dos gastos filtra tabela e cartões sem alterar total persistido',()=>{const {run,document}=app();run("filtro.gastosMes='2026-09';E.gastos=[{id:'a',mes:'2026-09',oque:'Mercado',valor:120,classe:'Casa'},{id:'b',mes:'2026-09',oque:'Consulta',valor:300,classe:'Saúde'}]");mount(run,'vGastos');const b=document.querySelector('[data-bid=gt-lista]'),inp=b.querySelector('.ff-list-filter input');inp.value='consulta';inp.oninput();assert.equal([...b.querySelectorAll('tbody > tr')].filter(x=>!x.hidden).length,1);assert.equal(b.querySelector('[data-ff-gasto=a]').hidden,true);assert.match(b.querySelector('[role=status]').textContent,/300,00/);assert.equal(run('E.gastos.length'),2)});
test('Caixa mantém fórmulas e apresenta datas da posição e busca vinculada à linha',()=>{const {run,document}=app();run("E.contas=[{id:'b',nome:'Banco',tipo:'Dinheiro',valor:100,atualizacao:'2026-09-10'},{id:'c',nome:'Cheque',tipo:'Cheque',valor:30,atualizacao:''}];E.empreend=[{id:'e',nome:'Projeto',vgv:1000,aporteResidual:20,aporteTotal:40,previsao:0}]");const antes=run('JSON.stringify(contasVGV())');mount(run,'vCaixaVGV');run('organizarCaixaVGV(pagina)');assert.match(document.querySelector('.ff-source-quality').textContent,/10\/09\/2026/);assert.match(document.querySelector('.ff-source-quality').textContent,/1 contas sem data/);const bloco=document.querySelector('[data-bid=cx-contas]'),inp=bloco.querySelector('.ff-list-filter input');inp.value='Cheque';inp.oninput();assert.equal([...bloco.querySelectorAll('tbody > tr')].filter(x=>!x.hidden).length,1);assert.equal(run('JSON.stringify(contasVGV())'),antes);assert.equal(run('contasVGV().aInvestirLiq'),80)});
test('Categorias com estorno de valor igual não exibem NaN ou Infinity',()=>{const {run,document}=app();run("filtro.gastosMes='2026-09';E.casa=[];E.assinaturas=[];E.seguros=[];E.planos=[];E.gastos=[{id:'a',mes:'2026-09',oque:'Compra',valor:100,classe:'Casa'},{id:'b',mes:'2026-09',oque:'Estorno',valor:-100,classe:'Casa'}]");mount(run,'vGastos');assert.doesNotMatch(document.querySelector('[data-bid=gt-classe]').textContent,/NaN|Infinity/)});
test('Excluir gasto para quando os comprovantes não podem ser removidos',async()=>{const {run,document}=app();run("filtro.gastosMes='2026-09';E.gastos=[{id:'g',mes:'2026-09',oque:'Mercado',valor:10}];confirm=()=>true;apagarAnexosDe=async()=>false");mount(run,'vGastos');await document.querySelector('[data-ff-gasto=g] .btn').onclick();assert.equal(run('E.gastos.length'),1)});
test('Bem: prévia do saldo acompanha edição sem alterar o valor salvo',()=>{const {run,document}=app();run("E.patrimonio=[{id:'a',nome:'Apartamento',tipo:'Imóvel',valor:100,falta:20,situacao:'Financiado'}];modalBem(E.patrimonio[0])");const f=form(document);fill(f,'valor','200');f.querySelector('[name=valor]').oninput();assert.match(document.querySelector('.ff-equity-preview').textContent,/180,00/);assert.equal(run('E.patrimonio[0].valor'),100)});
test('Todos os anos mantém o período na origem selecionada e informa contagem completa',()=>{const {run,document}=app();run("E.rendimentos=[{id:'a',data:'2024-03-12',empresa:'Aplicação',valor:20},{id:'b',data:'2026-09-12',empresa:'Aplicação',valor:80}];filtro.rendAno='todos';filtro.rendVisao='Mensal'");mount(run,'vRendimentos');assert.ok([...document.querySelectorAll('option')].some(o=>o.textContent==='Aplicação (2)'));assert.equal(document.querySelector('[data-bid=rd-mes]'),null);assert.ok(document.querySelector('[data-bid=rd-dash]'));const k=document.querySelector('[data-kpi=fonte]');assert.ok(k);k.onclick();assert.equal(run('filtro.rendAno'),'todos')});
test('Editar gasto antigo preserva a categoria do formato legado',()=>{const {run,document}=app();run("E.gastos=[{id:'legado',mes:'2026-09',categoria:'Lazer',oque:'Cinema',valor:100}];modalLancamentoGasto(E.gastos[0])");fill(form(document),'obs','Conferido');submit(form(document));assert.equal(run("E.gastos[0].classe||E.gastos[0].categoria"),'Lazer')});

test('Gastos organiza categorias sem alterar dados e permite adicionar dentro do grupo',()=>{
 const {run,document}=app();
 run("E.config.catGasto=['Casa','Lazer'];E.gastos=[{id:'a',mes:'2026-09',classe:'Casa',oque:'Copasa',valor:70},{id:'b',mes:'2026-09',classe:'Casa',oque:'Cemig',valor:130},{id:'c',mes:'2026-09',categoria:'Lazer',oque:'Cinema',valor:40}];filtro.gastosMes='2026-09';var antes=JSON.stringify(E.gastos)");
 mount(run,'vGastos');
 const casa=[...document.querySelectorAll('.gasto-categoria')].find(x=>x.querySelector('summary').textContent.includes('Casa'));
 assert.match(casa.textContent,/Copasa/);assert.match(casa.textContent,/Cemig/);assert.match(casa.querySelector('summary').textContent,/200,00/);
 assert.equal(document.querySelectorAll('.gastos-categorias [data-ff-gasto]').length,3);
 const filhos=[...document.querySelectorAll('.gasto-categoria')].find(x=>x.querySelector('summary').textContent.includes('Filhos'));
 filhos.querySelector('button').onclick();
 assert.ok([...form(document).querySelector('[name=classe]').options].some(x=>x.value==='Filhos'));
 assert.equal(run('JSON.stringify(E.gastos)'),run('antes'));
});
