import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
const fonte=readFileSync(new URL('../publico/organograma.js',import.meta.url),'utf8');
const exemplo=()=>({id:'grupo',titulo:'Grupo de teste',nos:[{id:'a',nome:'Antigo',empresaId:'empresa-a',tipo:'Holding',parentId:''},{id:'b',nome:'Empresa B',tipo:'Empresa',parentId:'a',socios:'Pessoa exemplo — 100%',observacoes:'Registro original'},{id:'c',nome:'Equipe',tipo:'Área',parentId:'b'}]});
function app(estado){const {document,HTMLElement,HTMLSelectElement}=parseHTML('<html><body><main></main><div id="modal"></div></body></html>');Object.defineProperty(HTMLSelectElement.prototype,'value',{configurable:true,get(){return [...this.options].find(o=>o.selected)?.value || this.options[0]?.value || ''},set(v){for(const o of this.options)o.selected=o.value===String(v)}});HTMLElement.prototype.scrollIntoView=function(){};const ctx=vm.createContext({document,console,URL,Date,Math,Set,Map});vm.runInContext(fonte,ctx);const api=ctx.LeoOrganograma,e=estado||{empresasPJ:[{id:'empresa-a',nome:'Atual'}],organogramas:[exemplo()]},calls=[];const contexto={getState:()=>e,save:()=>calls.push('save'),onSelect:id=>calls.push(id),openModal:(titulo,sub,montar)=>{const m=document.querySelector('#modal');m.replaceChildren();const c=document.createElement('div');m.append(c);montar(c,()=>m.replaceChildren())}};return{api,e,document,contexto,calls,render(){return api.render(document.querySelector('main'),contexto)}}}
const plain=v=>JSON.parse(JSON.stringify(v));
function clicar(a,nome,root='body'){const b=[...a.document.querySelectorAll(root+' button')].find(b=>b.textContent===nome);assert.ok(b,`Botão ${nome}`);b.click()}
function enviar(a,dados){const f=a.document.querySelector('#modal form');for(const[k,v]of Object.entries(dados))f.querySelector(`[name=${k}]`).value=String(v);f.onsubmit({preventDefault(){}})}
test('Validação aceita florestas e não converte ligação visual em participação',()=>{const {api}=app(),o=exemplo();o.nos.push({id:'livre',nome:'Outra raiz'});api.validar([o]);assert.equal(o.nos[1].percentual,undefined);assert.equal(o.nos[0].socios,undefined)});
test('Ciclos diretos, indiretos, referências ausentes e IDs repetidos são rejeitados',()=>{const {api}=app();for(const mudar of [o=>o.nos[0].parentId='a',o=>o.nos[0].parentId='c',o=>o.nos[1].parentId='inexistente',o=>o.nos.push({...o.nos[0]})]){const o=exemplo();mudar(o);assert.throws(()=>api.validar([o]))}});
test('Tipos inválidos e percentuais fora do intervalo são rejeitados',()=>{const {api}=app();for(const percentual of [-1,101,NaN,'12',Infinity]){const o=exemplo();o.nos[0].percentual=percentual;assert.throws(()=>api.validar([o]))}for(const percentual of [0,100,12.5,'']){const o=exemplo();o.nos[0].percentual=percentual;api.validar([o])}});
test('Salvar item faz cópia e mantém campos históricos, sem alterar registro original',()=>{const {api}=app(),o=exemplo(),antes=JSON.stringify(o),novo=api.salvarNo(o,{...o.nos[1],nome:'Editado',banco:'Banco de referência'});assert.equal(JSON.stringify(o),antes);assert.equal(novo.nos[1].socios,o.nos[1].socios);assert.equal(novo.nos[1].nome,'Editado');assert.ok(novo.atualizadoEm)});
test('Remover item mantém descendentes ligados ao nível superior, sem órfãos',()=>{const {api}=app(),o=exemplo(),novo=api.removerNo(o,'b');assert.equal(novo.nos.length,2);assert.equal(novo.nos.find(n=>n.id==='c').parentId,'a');assert.equal(o.nos.length,3);api.validar([novo]);const semRaiz=api.removerNo(o,'a');assert.equal(semRaiz.nos.find(n=>n.id==='b').parentId,'')});
test('Remover ou recortar ID inexistente é rejeitado sem mutação',()=>{const {api}=app(),o=exemplo(),antes=JSON.stringify(o);assert.throws(()=>api.removerNo(o,'x'));assert.throws(()=>api.recorte(o,'x'));assert.equal(JSON.stringify(o),antes)});
test('Recorte inclui descendentes e exclui irmãos sem modificar ligações originais',()=>{const {api}=app(),o=exemplo();o.nos.push({id:'irma',nome:'Irmã',parentId:'a'});const parte=api.recorte(o,'b');assert.deepEqual(plain(parte.nos.map(n=>n.id)),['b','c']);assert.equal(parte.nos[0].parentId,'');assert.equal(o.nos[1].parentId,'a')});
test('Nome e logo vêm do cadastro vivo por ID, com fallback explícito quando ausente',()=>{const {api,e}=app(),n=exemplo().nos[0];assert.equal(api.identificar(n,e).nome,'Atual');e.empresasPJ[0].nome='Renomeada';assert.equal(api.identificar(n,e).nome,'Renomeada');e.empresasPJ=[];const i=api.identificar(n,e);assert.equal(i.nome,'Antigo');assert.equal(i.ausente,true)});
test('Logos seguras e fundo HEX preservados; scripts e credenciais recusados',()=>{const {api}=app(),o=exemplo();o.nos[0].logo='data:image/png;base64,YWJj';o.nos[0].logoFundo='#12141f';api.validar([o]);assert.equal(api.identificar(o.nos[0],{empresasPJ:[]}).logoFundo,'#12141f');for(const logo of ['javascript:alert(1)','data:image/svg+xml;base64,YWJj','https://usuario:senha@example.com/logo.png']){o.nos[0].logo=logo;assert.throws(()=>api.validar([o]))}o.nos[0].logo='https://example.com/logo.png';o.nos[0].logoFundo='red; color:black';assert.throws(()=>api.validar([o]))});
test('Importação aceita pacote ou diagrama único e não substitui ID existente',()=>{const {api,e}=app(),o=exemplo(),antes=JSON.stringify(e);assert.equal(api.listaImportacao(JSON.stringify(o)).length,1);const l=api.listaImportacao({organogramas:[o]}),nova=api.importarNoEstado(e,l);assert.equal(nova.length,2);assert.equal(nova[0].id,'grupo');assert.notEqual(nova[1].id,'grupo');assert.equal(JSON.stringify(e),antes);assert.equal(l[0].id,'grupo')});
test('Exportação escapa texto, preserva campos da referência e não insere HTML externo',()=>{const {api,e}=app(),o=exemplo();o.titulo='<script>segredo</script>';Object.assign(o.nos[1],{cnpj:'00.000.000/0000-00',regime:'Referência tributária',banco:'Banco teste',contabilidade:'Escritório teste',atividade:'Atividade teste',observacoes:'<img src=x onerror=alert(1)>'});const html=api.htmlExportacao(o,e);assert.ok(html.includes('&lt;script&gt;segredo&lt;/script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img src=x'));for(const v of ['Banco teste','Escritório teste','Atividade teste','Referência tributária','Pessoa exemplo'])assert.ok(html.includes(v));assert.ok(html.includes('size:A3 landscape'))});
test('Exportação de parte exclui nós externos e pode omitir observações',()=>{const {api,e}=app(),o=exemplo();o.observacoes='Nota geral secreta';const html=api.htmlExportacao(o,e,{raizId:'c',notas:false});assert.ok(html.includes('Equipe'));assert.ok(!html.includes('Empresa B'));assert.ok(!html.includes('Nota geral secreta'));assert.ok(!html.includes('Registro original'))});
test('Estrutura grande preserva todos os textos com páginas de leitura',()=>{const {api,e}=app(),o={id:'g',titulo:'Estrutura extensa',nos:[{id:'r',nome:'Raiz'}]};for(let i=0;i<15;i++)o.nos.push({id:'n'+i,nome:'Empresa número '+i,parentId:'r',observacoes:'Observação completa '+i});const html=api.htmlExportacao(o,e);assert.ok(html.includes('Leitura dos itens'));for(let i=0;i<15;i++)assert.ok(html.includes('Observação completa '+i));assert.ok(!html.includes('overflow:hidden'))});
test('Tema escuro usa cores legíveis e fundo importado da logo',()=>{const {api,e}=app(),o=exemplo();o.tema='escuro';Object.assign(o.nos[1],{logo:'data:image/png;base64,YWJj',logoFundo:'#12141f'});const html=api.htmlExportacao(o,e);assert.ok(html.includes('class="escuro"'));assert.ok(html.includes('fill="#12141f"'));assert.ok(html.includes('fill="#f5f7fa"'))});
test('Formulário cancelar item deixa estado e salvamento intocados',()=>{const a=app(),antes=JSON.stringify(a.e);a.render();clicar(a,'+ Adicionar item');a.document.querySelector('[name=nome]').value='Rascunho';clicar(a,'Cancelar','#modal');assert.equal(JSON.stringify(a.e),antes);assert.ok(!a.calls.includes('save'))});
test('Formulário novo item vinculado usa nome canônico e grava apenas ao salvar',()=>{const a=app();a.render();clicar(a,'+ Adicionar item');enviar(a,{empresaId:'empresa-a',nome:'Nome ignorado',tipo:'Empresa',parentId:'b',percentual:''});assert.equal(a.document.querySelector('.org-erro')?.textContent||'','');assert.equal(a.e.organogramas[0].nos.length,4);assert.equal(a.e.organogramas[0].nos[3].nome,'Atual');assert.equal(a.e.organogramas[0].nos[3].empresaId,'empresa-a');assert.ok(a.calls.includes('save'))});
test('Falha ao persistir mantém estado anterior e modal aberto com erro',()=>{const a=app();a.contexto.save=()=>{a.e._mt=123;throw Error('Armazenamento cheio')};a.render();const antes=JSON.stringify(a.e);clicar(a,'+ Adicionar item');enviar(a,{nome:'Novo',tipo:'Área'});assert.equal(JSON.stringify(a.e),antes);assert.match(a.document.querySelector('#modal .org-erro').textContent,/Armazenamento cheio/);assert.ok(a.document.querySelector('#modal form'))});
test('Seleção de outro organograma notifica contexto e pode sobreviver à reabertura',()=>{const a=app();a.e.organogramas.push({id:'segundo',titulo:'Segundo grupo',nos:[]});a.render();const select=a.document.querySelector('.org-barra select');select.value='segundo';select.onchange();assert.equal(a.calls.at(-1),'segundo');a.contexto.selectedId='segundo';a.render();assert.equal(a.document.querySelector('.org-painel-cab h3').textContent,'Segundo grupo')});
test('Importação aguarda aprovação e cancelamento preserva dados',async()=>{const a=app(),controle=a.render(),antes=JSON.stringify(a.e);controle.importarArquivo({size:123,text:async()=>JSON.stringify({id:'nova',titulo:'Importado',nos:[]})});await Promise.resolve();assert.match(a.document.querySelector('#modal').textContent,/Nada foi salvo/);clicar(a,'Cancelar','#modal');assert.equal(JSON.stringify(a.e),antes)});
test('Cancelar enquanto arquivo é lido não monta prévia depois do fechamento',async()=>{const a=app(),controle=a.render();let resolver;controle.importarArquivo({size:1,text:()=>new Promise(r=>resolver=r)});a.document.querySelector('#modal').replaceChildren();resolver(JSON.stringify(exemplo()));await Promise.resolve();assert.equal(a.document.querySelector('#modal').textContent,'');assert.equal(a.e.organogramas.length,1)});
test('Falha de salvamento da importação restaura o estado e permite tentar novamente',async()=>{const a=app(),controle=a.render(),antes=JSON.stringify(a.e);a.contexto.save=()=>{throw Error('Sem espaço')};controle.importarArquivo({size:1,text:async()=>JSON.stringify(exemplo())});await Promise.resolve();clicar(a,'Salvar importação','#modal');assert.equal(JSON.stringify(a.e),antes);assert.match(a.document.querySelector('#modal .org-erro').textContent,/Sem espaço/)});
test('Salvar rascunho desatualizado não sobrescreve alterações recebidas',()=>{const a=app();a.render();clicar(a,'+ Adicionar item');a.e.organogramas[0].observacoes='Mudança recebida';const antes=JSON.stringify(a.e);enviar(a,{nome:'Rascunho antigo',tipo:'Área'});assert.equal(JSON.stringify(a.e),antes);assert.match(a.document.querySelector('#modal .org-erro').textContent,/mudou enquanto/)});
test('Importações grandes e hierarquias excessivas são rejeitadas antes de desenhar',()=>{const {api}=app();const lista=Array.from({length:51},(_,i)=>({id:'g'+i,titulo:'Grupo',nos:[]}));assert.throws(()=>api.validar(lista),/50 organogramas/);const o={id:'g',titulo:'Grande',nos:Array.from({length:201},(_,i)=>({id:'n'+i,nome:'Item'}))};assert.throws(()=>api.validar([o]),/200 itens/);o.nos=Array.from({length:21},(_,i)=>({id:'n'+i,nome:'Item',parentId:i?'n'+(i-1):''}));assert.throws(()=>api.validar([o]),/20 níveis/)});
test('Visão geral mostra todos os nós e permite edição por teclado; detalhar mantém ações',()=>{const a=app();a.render();assert.equal(a.document.querySelectorAll('.org-visao-geral [data-no-id]').length,3);const alvo=a.document.querySelector('.org-visao-geral [data-no-id=b]');assert.equal(alvo.getAttribute('role'),'button');assert.equal(alvo.getAttribute('tabindex'),'0');a.document.querySelector('.org-visao-geral').onkeydown({target:alvo,key:'Enter',preventDefault(){}});assert.equal(a.document.querySelector('#modal [name=nome]').value,'Empresa B');clicar(a,'Cancelar','#modal');clicar(a,'Detalhar');assert.equal(a.document.querySelector('.org-viewport').hidden,false);assert.equal(a.document.querySelectorAll('.org-no').length,3)});
test('Leitura exportada preserva textos longos sem acrescentar espaços',()=>{const {api,e}=app(),o=exemplo(),texto='https://exemplo.test/'+('a'.repeat(90));o.nos[1].observacoes=texto;assert.ok(api.htmlExportacao(o,e).includes(texto))});
test('Estrutura compacta com 12 itens usa colunas verticais sem sobrepor caixas',()=>{const {api,e}=app(),o={id:'g',titulo:'Grupo de exemplo',nos:[{id:'r',nome:'Grupo',tipo:'Holding'}]};for(let i=0;i<5;i++)o.nos.push({id:'p'+i,nome:'Empresa principal '+i,parentId:'r',logo:'data:image/png;base64,YWJj'});for(let i=0;i<4;i++)o.nos.push({id:'s'+i,nome:'Empresa secundária '+i,parentId:'p0',logo:'data:image/png;base64,YWJj'});o.nos.push({id:'neto',nome:'Projeto',parentId:'s1'},{id:'area',nome:'Área',parentId:'p4'});const d=api.diagramaSVG(o,e,{resumo:true});assert.ok(d.largura<=1700);assert.ok(d.altura<=1000);const {document}=parseHTML(d.svg),caixas=[...document.querySelectorAll('[data-no-id]')].map(g=>{const r=g.querySelector('rect');return{x:+r.getAttribute('x'),y:+r.getAttribute('y'),w:+r.getAttribute('width'),h:+r.getAttribute('height')}});assert.equal(caixas.length,12);for(let i=0;i<caixas.length;i++)for(let j=i+1;j<caixas.length;j++){const a=caixas[i],b=caixas[j];assert.ok(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y,'Caixas precisam permanecer separadas')}});
test('Notas de exportação aparecem uma vez antes dos itens e não ficam órfãs',()=>{const {api,e}=app(),o=exemplo();o.tema='escuro';o.observacoes='Nota única de conferência';const html=api.htmlExportacao(o,e);assert.equal(html.split('Nota única de conferência').length,2);assert.ok(html.indexOf('Nota única de conferência')<html.indexOf('<div class="grade">'));assert.ok(html.includes('page-break-inside:avoid'));assert.ok(html.includes('.detalhes>p,.vinculo){color:#bbc4d2}'))});
test('PDF distribui irmãos horizontalmente também nos níveis internos e no recorte',()=>{
  const {api,e}=app(),o=exemplo();
  o.nos.push({id:'d',nome:'Outra equipe',parentId:'b'});
  const antes=JSON.stringify(o);
  for(const opts of [{},{formato:'completo'},{raizId:'b'}]){
    const {document}=parseHTML(api.htmlExportacao(o,e,opts));
    const rect=id=>document.querySelector(`[data-no-id="${id}"] rect`);
    assert.equal(rect('c').getAttribute('y'),rect('d').getAttribute('y'));
    assert.ok(+rect('c').getAttribute('x')+272<=+rect('d').getAttribute('x'));
    assert.ok(+rect('b').getAttribute('y')<+rect('c').getAttribute('y'));
  }
  assert.equal(JSON.stringify(o),antes);
});
