import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers/dom.mjs';
function app(){const a=setup();a.run("E=structuredClone(SEED);E.oportunidades=[];E.agenda=[];E.documentos=[];E.pessoas=[];E.metas=[];E.pdi=[];E.desenvolvimento={};E.empresasPJ=[{id:'empresa',nome:'Alfa',status:'Ativa',banco:'Banco Azul'}];E.planejamentoEmpresas=[];E.estrategia={}");return a}
function submit(document,values,selector='.dev-form'){const f=document.querySelector(selector);assert.ok(f);for(const [k,v] of Object.entries(values)){const input=f.querySelector('[name="'+k+'"]');assert.ok(input,k);if(input.tagName==='SELECT'){[...input.options].forEach(o=>o.selected=false);[...input.options].find(o=>o.value===v).selected=true}else input.value=v}f.onsubmit({preventDefault(){}})}
test('Oportunidade só entra na comparação com os seis critérios respondidos',()=>{const {run}=app();assert.equal(run("respondida({ganho:5})"),false);assert.equal(run("respostasOport({ganho:5,animo:0})"),2);assert.equal(run("respondida({ganho:0,animo:0,encaixe:0,esforco:0,custo:0,risco:0})"),true);assert.equal(run("descricaoNotaOport({ganho:5,animo:0})"),'Avaliação 2/6')});
test('Notas inválidas, vazias ou fora da escala não completam avaliação',()=>{const {run}=app();for(const value of [null,'',6,-1,2.5,'x']){run('globalThis.v='+JSON.stringify(value));assert.equal(run("respondida({ganho:v,animo:0,encaixe:0,esforco:0,custo:0,risco:0})"),false)}});
test('Lista indica avaliação parcial, contador inclui pendência e ranking não inventa nota',()=>{const {run,document}=app();run("E.oportunidades=[{id:'o',titulo:'Ideia parcial',ganho:5,estagio:'Semente'}];atual='oportunidades';tela()");assert.match(document.querySelector('.workspace-opportunity').textContent,/Avaliação 1\/6/);assert.doesNotMatch(document.querySelector('#oport-comparar').textContent,/Ideia parcial/);assert.equal(run("E.oportunidades[0].risco"),undefined)});
test('Repetir próximo passo na Agenda não cria compromissos duplicados',()=>{const {run}=app();run("const o={id:'o',titulo:'Novo projeto',proximoPasso:'Conferir proposta',ate:'2026-10-10'};const a=agendarOportunidade(o);const b=agendarOportunidade(o)");assert.equal(run('E.agenda.length'),1);assert.equal(run('a.criado'),true);assert.equal(run('b.criado'),false);assert.equal(run('E.agenda[0].origemOportunidadeId'),'o')});
test('Compromisso já editado na Agenda é preservado ao reenviar o mesmo passo',()=>{const {run}=app();run("const o={id:'o',titulo:'Projeto',proximoPasso:'Telefonar',ate:'2026-10-10'};agendarOportunidade(o);E.agenda[0].titulo='Título ajustado';E.agenda[0].data='2026-11-11';const antes=JSON.stringify(E.agenda);agendarOportunidade(o)");assert.equal(run('JSON.stringify(E.agenda)===antes'),true)});
test('Passo diferente mantém compromissos anteriores e tem vínculo próprio',()=>{const {run}=app();run("const o={id:'o',titulo:'Projeto',proximoPasso:'Primeiro'};agendarOportunidade(o);o.proximoPasso='Segundo';agendarOportunidade(o)");assert.equal(run('E.agenda.length'),2);assert.equal(run('E.agenda[0].origemPasso'),'Primeiro')});
test('Evento legado da oportunidade não é duplicado nem alterado',()=>{const {run}=app();run("const o={id:'o',titulo:'Projeto',proximoPasso:'Primeiro',ate:'2026-10-10'};E.agenda=[{id:'antigo',titulo:'Primeiro — Projeto',data:'2026-10-10',obs:'veio das Oportunidades'}];const antes=JSON.stringify(E.agenda);const x=agendarOportunidade(o)");assert.equal(run('x.criado'),false);assert.equal(run('JSON.stringify(E.agenda)===antes'),true)});
test('Não agenda uma oportunidade sem próximo passo',()=>{const {run}=app();assert.throws(()=>run("agendarOportunidade({id:'o',titulo:'Ideia'})"),/próximo passo/);assert.equal(run('E.agenda.length'),0)});
for(const [func,lista,nome] of [['novoDocumento','documentos','documento'],['novaOportunidade','oportunidades','oportunidade'],['novaMeta','metas','meta'],['novaPessoa','pessoas','pessoa']])test('Cancelar cadastro de '+nome+' não grava um registro vazio',()=>{const {run,document}=app();run(func+'()');assert.equal(run('E.'+lista+'.length'),0);document.querySelector('.fechar').click();assert.equal(run('E.'+lista+'.length'),0)});
test('Documento aceita nome específico e só é persistido após confirmação',()=>{const {run,document}=app();run('novoDocumento()');submit(document,{nome:'Contrato de locação Alfa',dono:'Léo',numero:'DOC-7',onde:'Arquivo azul'});assert.equal(run('E.documentos.length'),1);assert.equal(run('E.documentos[0].nome'),'Contrato de locação Alfa');assert.equal(run('E.documentos[0].onde'),'Arquivo azul');assert.ok(document.querySelector('.solta'))});
test('Documento sem nome não é criado e indica campo faltante',()=>{const {run,document}=app();run('novoDocumento()');submit(document,{nome:'   '});assert.equal(run('E.documentos.length'),0);assert.match(document.querySelector('.dev-erro').textContent,/nome/)});
test('Nova meta registra o primeiro passo sem converter contexto em resultado',()=>{const {run,document}=app();run('novaMeta()');submit(document,{meta:'Aprender francês',primeiroPasso:'Pesquisar uma escola'});assert.equal(run('E.metas.length'),1);assert.equal(run('E.metas[0].passos.length'),1);assert.equal(run('E.metas[0].passos[0].feito'),false);assert.equal(run('E.metas[0].passos[0].texto'),'Pesquisar uma escola')});
test('Pessoa com nascimento futuro não é cadastrada',()=>{const {run,document}=app();run('novaPessoa()');submit(document,{nome:'Pessoa de teste',nascimento:'2099-01-01'});assert.equal(run('E.pessoas.length'),0);assert.match(document.querySelector('.dev-erro').textContent,/futuro/)});
test('Editor preserva área personalizada fora da lista atual',()=>{const {run,document}=app();run("E.pdi=[{id:'p',habilidade:'Prática',area:'Área antiga especial',status:'Praticando'}];devModalAcao(E.pdi[0])");assert.equal(document.querySelector('[name=area]').value,'Área antiga especial');submit(document,{habilidade:'Prática revisada'});assert.equal(run('E.pdi[0].area'),'Área antiga especial')});
test('Levar uma análise ao plano cria rascunho e cancelar não altera PDI',()=>{const {run,document}=app();run("const l={id:'l',titulo:'Escutar',passo:'Ouvir'};const p=devCriarAcao(l,false);devModalAcao(p)");assert.equal(run('E.pdi.length'),0);document.querySelector('.fechar').click();assert.equal(run('E.pdi.length'),0)});
test('Confirmar prática ligada a análise preserva vínculo e não duplica',()=>{const {run,document}=app();run("const l={id:'l',titulo:'Escutar',passo:'Ouvir'};const p=devCriarAcao(l,false);devModalAcao(p)");submit(document,{habilidade:'Escutar'});assert.equal(run('E.pdi.length'),1);assert.equal(run('E.pdi[0].leituraId'),'l');assert.equal(run("devCriarAcao(l,false).id===p.id"),true)});
test('Resultado da prática guarda prática, análise e evidência por referências explícitas',()=>{const {run,document}=app();run("devDados().leituras=[{id:'l',titulo:'Análise',fontes:[]}];E.pdi=[{id:'p',habilidade:'Delegar',como:'Combinar autonomia',leituraId:'l'}];devModalResultado('l',E.pdi[0])");submit(document,{data:'2026-08-01',resultado:'Combinado seguido',evidencia:'Exemplo descrito'});assert.equal(run('devDados().resultados[0].pdiId'),'p');assert.equal(run('devDados().resultados[0].leituraId'),'l');assert.equal(run('devDados().resultados[0].contexto'),'Combinar autonomia');assert.equal(run('E.pdi[0].status'),undefined)});
test('Todos os resultados e contextos permanecem abertos numa sequência única',()=>{const {run,document}=app();run("devDados().fontes=[{id:'f',titulo:'Relatório',revisado:true,disc:{natural:{D:71}},resumo:'Texto original',limites:'Contexto integral'}];devDados().leituras=[{id:'l',titulo:'Leitura',texto:'Texto completo',status:'Não me representa'}];atual='guia';filtro.guiaAba='desenvolvimento';filtro.devAba='resultados';tela()");const host=document.querySelector('#dev-resultados');assert.equal(host.querySelector('details'),null);assert.equal(host.querySelectorAll('.dev-stream-section').length,4);assert.match(host.textContent,/Contexto integral/);assert.match(host.textContent,/Não me representa/);assert.equal(host.querySelectorAll('.planos-stream-links button').length,4);host.querySelector('.planos-stream-links button').click();for(const pane of host.querySelectorAll('.dev-stream-section'))assert.equal(pane.hidden,false)});
test('Resumo de desenvolvimento distingue prática, conferência e registro sem evidência',()=>{const {run}=app();run("devDados().leituras=[{id:'l',status:'A conferir'},{id:'l2',status:'Reconheço'}];E.pdi=[{id:'p',habilidade:'Prática',ate:'2020-01-01',status:'Praticando'},{id:'p2',habilidade:'Concluída',status:'Dominado'}];devDados().resultados=[{id:'r',resultado:'Registro sem evidência'}];const s=devResumoAndamento()");assert.equal(run('s.conferir'),1);assert.equal(run('s.praticas'),1);assert.equal(run('s.revisar'),1);assert.equal(run('s.semEvidencia'),1)});
test('Conta no mesmo banco ou titular parecido não é atribuída à empresa',()=>{const {run}=app();run("E.bancos=[{id:'a',banco:'Banco Azul',titular:'Outra empresa'},{id:'b',titular:'Alfa Comercial'},{id:'c',titular:'ALFA'},{id:'d',empresaId:'empresa',titular:'Nome anterior'},{id:'e',empresaId:'outra',titular:'Alfa'}]");assert.equal(run("contasDaEmpresa(E.empresasPJ[0]).map(x=>x.id).join(',')"),'c,d');assert.equal(run('E.bancos.length'),5)});
test('Resultado anterior sem data fica preservado sem data inventada',()=>{const {run}=app();run("const p=criarPlanoEmpresa('empresa',2027);const o={id:'o',resultado:'Registro anterior',acoes:[]};p.objetivos=[o];registrarResultadoObjetivo(p,o,{resultado:'Novo resultado',resultadoEm:'2026-08-01'})");assert.equal(run('o.historicoResultados.length'),2);assert.equal(run("o.historicoResultados.find(x=>x.resultado==='Registro anterior').resultadoEm"),'');assert.equal(run('o.resultado'),'Novo resultado')});
test('Histórico de resultados não cresce ao salvar exatamente a mesma verificação',()=>{const {run}=app();run("const p=criarPlanoEmpresa('empresa',2027);const o={id:'o',acoes:[]};p.objetivos=[o];registrarResultadoObjetivo(p,o,{resultado:'25%',resultadoEm:'2026-08-01'});registrarResultadoObjetivo(p,o,{resultado:'25%',resultadoEm:'2026-08-01'})");assert.equal(run('o.historicoResultados.length'),1)});
test('Plano encerrado não aceita novo resultado por caminho direto',()=>{const {run}=app();run("const p=criarPlanoEmpresa('empresa',2027);const o={id:'o',resultado:'Preservado',acoes:[]};p.objetivos=[o];p.encerrado=true");assert.throws(()=>run("registrarResultadoObjetivo(p,o,{resultado:'Não salvar',resultadoEm:'2026-08-01'})"),/Reabra/);assert.equal(run('o.resultado'),'Preservado')});
test('Histórico anual não é transportado como resultado no ano seguinte',()=>{const {run}=app();run("const p=criarPlanoEmpresa('empresa',2027);p.objetivos=[{id:'o',titulo:'Objetivo',acoes:[]}];registrarResultadoObjetivo(p,p.objetivos[0],{resultado:'Resultado original',resultadoEm:'2026-08-01'});const copia=criarPlanoEmpresa('empresa',2028,p.id)");assert.equal(run('copia.objetivos[0].historicoResultados.length'),0);assert.equal(run('p.objetivos[0].historicoResultados.length'),1)});
test('PDF inclui histórico inteiro e não muda o registro original',()=>{const {run}=app();run("const p=criarPlanoEmpresa('empresa',2027);p.objetivos=[{id:'o',titulo:'Objetivo',resultado:'Anterior sem data',acoes:[]}];registrarResultadoObjetivo(p,p.objetivos[0],{resultado:'Resultado novo',resultadoEm:'2026-08-01'});const antes=JSON.stringify(p);const pdf=htmlPlanoApresentacao(E.empresasPJ[0],p)");assert.match(run('pdf'),/Anterior sem data/);assert.match(run('pdf'),/Resultado novo/);assert.match(run('pdf'),/Data não informada/);assert.equal(run('JSON.stringify(p)===antes'),true)});
test('Atalho da revisão limpa filtros antigos para mostrar o objetivo de destino',()=>{const {run,document}=app();run("const p=criarPlanoEmpresa('empresa',2027);p.objetivos=[{id:'o',titulo:'Prioridade',acoes:[{id:'a',oque:'Ação',status:'Travada'}]}];atual='estrategia';filtro.estrBusca='não existe';filtro.estrFiltro='atrasadas';tela()");document.querySelector('.planos-review-queue button').click();assert.equal(run('filtro.estrBusca'),'');assert.equal(run('filtro.estrFiltro'),'todas');assert.equal(document.querySelector('.strategy-objective').hasAttribute('open'),true)});
test('Card de ações abertas abre o filtro certo e exclui objetivos concluídos',()=>{const {run,document}=app();run("const p=criarPlanoEmpresa('empresa',2027);p.objetivos=[{id:'o1',titulo:'Aberto',acoes:[{id:'a',oque:'Ação',status:'A fazer'}]},{id:'o2',titulo:'Fechado',acoes:[{id:'b',oque:'Terminou',status:'Feita'}]}];atual='estrategia';tela()");document.querySelectorAll('.strategy-numbers button')[1].click();assert.equal(run('filtro.estrFiltro'),'abertas');assert.equal(document.querySelectorAll('.strategy-objective').length,1);assert.match(document.querySelector('.strategy-objective').textContent,/Aberto/)});
test('Meta com horizonte antigo continua visível no Guia',()=>{const {run,document}=app();run("E.metas=[{id:'m',meta:'Meta preservada',horizonte:'Horizonte antigo',area:'Pessoal',status:'Aberta',passos:[]}];atual='guia';tela()");assert.match(document.querySelector('[data-bid=gu-metas]').textContent,/Meta preservada/);assert.match(document.querySelector('[data-bid=gu-metas]').textContent,/Horizonte antigo/)});
test('Plano pessoal de área antiga continua visível sem reclassificar dado',()=>{const {run,document}=app();run("E.planoAno=[{id:'p',ano:2027,area:'Área antiga',oque:'Plano preservado'}];filtro.planoAno=2027;atual='guia';tela()");assert.match(document.querySelector('[data-bid=gu-plano]').textContent,/Plano preservado/);assert.equal(run('E.planoAno[0].area'),'Área antiga')});

test('Validade inválida não aparece como documento em dia',()=>{const {run,document}=app();run("E.documentos=[{id:'a',nome:'Vencimento inválido',validade:'2026-02-31'},{id:'b',nome:'Sem data'},{id:'c',nome:'Outro inválido',validade:'não é data'}];filtro.docStatus='Conferir validade';atual='documentos';tela()");assert.equal(run("statusDocumento(E.documentos[0])"),'Data inválida');assert.equal(document.querySelectorAll('.workspace-document').length,3);assert.equal(run("statusDocumento({validade:'2028-02-29'})"),'Em dia')});
test('Vencimento em exatamente 180 dias entra no aviso de até 180 dias',()=>{const {run}=app();run("const data180=new Date(hoje()+'T12:00');data180.setDate(data180.getDate()+180);const validade=[data180.getFullYear(),String(data180.getMonth()+1).padStart(2,'0'),String(data180.getDate()).padStart(2,'0')].join('-')");assert.equal(run('statusDocumento({validade})'),'Vencendo')});

for(const [func,lista] of [['novoRitual','rituais'],['novaIdeiaParaEles','paraEles']])test('Cancelar '+func+' preserva a lista sem cadastro vazio',()=>{const {run,document}=app();run('E.'+lista+'=[];'+func+'()');document.querySelector('.fechar').click();assert.equal(run('E.'+lista+'.length'),0)});
test('Ritual e ideia familiar são guardados somente ao confirmar',()=>{const {run,document}=app();run('E.rituais=[];E.paraEles=[];novoRitual()');submit(document,{ritual:'Almoço em família',comQuem:'Família',frequencia:'Mensal'});assert.equal(run('E.rituais[0].ritual'),'Almoço em família');assert.equal(run('E.rituais[0].ultima'),'');run('novaIdeiaParaEles()');submit(document,{oque:'Passeio de bicicleta',pessoa:'Filhos'});assert.equal(run('E.paraEles[0].oque'),'Passeio de bicicleta');assert.equal(run('E.paraEles[0].status'),'Ideia')});
